### ISSUE TITLE
rnv can't find connected device

### ISSUE THREAD

**Issue by aurimasmi** [flexn-io/renative#1018]
**Describe the bug**
RNV can't find tvos(might be happening with other devices also) device even if it's connected and xcode shows it

**To Reproduce**
1. Connect tvos device to your computer via cable
2. Optional - open xcode to see if it's really connected
3. Run `npx rnv run -p tvos -d`

**Expected behavior**
Device is connected and rnv can find it

**Screenshots or copy&paste**
![CleanShot2023-06-19at12 18 58](https://github.com/flexn-io/renative/assets/16107073/5f57daf0-adbc-4b50-b280-df5bf6eefc43)

**Desktop (please complete the following information):**

-   OS: osx
-   Node Version v16.18.0
-   RNV Version 0.37.0-canary.11

**Comment by GabrieleKaceviciute** [comment]
Same issue with ios.
I've tested on RNV Version: 0.37.0-rc.1
