### ISSUE TITLE
Can't ran tvos and ios on emulator

### ISSUE THREAD

**Issue by aurimasmi** [flexn-io/renative#1019]
**Describe the bug**
Tvos and Ios apps can't run on arm architecture.Reproducable only on M1/M2. Seems started from macos Ventura.

**To Reproduce**
Build ios, tvos app, add an example Crashlytics plugin and try to run it on emulator

**Expected behavior**
App runs

**Screenshots or copy&paste**
![CleanShot2023-06-19at12 15 32](https://github.com/flexn-io/renative/assets/16107073/f56203cd-3185-4377-ae43-7cfd62696a0c)

**Desktop (please complete the following information):**

-   OS: osx
-   Node Version v16.18.0
-   RNV Version 0.37.0-canary.11

**Comment by ElenaDiachenko** [comment]
RNV Version 0.38.0-canary(upgrade-ts-3): ios runs successfully, tvos doesn't work

**Comment by pauliusguzas** [comment]
@aurimasmi could you test yourself on latest rc or add instruction how to add that crashlytics plugin?

**Comment by aurimasmi** [comment]
There is crashlytics in [@flexn scoped plugins](https://github.com/flexn-io/commonwealth/blob/main/packages/plugins/pluginTemplates/renative.plugins.json#L638) you should be able to add it just by defining it in your renative.json:

```
plugins: {
  "@react-native-firebase/crashlytics": "source:flexn"
}
```

**Comment by pauliusguzas** [comment]
@aurimasmi it works with 1.0.0-rc.6 but noticed that first time build with crashlytics added takes more than 5 minutes, second time even with -r is a lot faster, so is this expected? cc @mihaiblaga89
