### ISSUE TITLE
Metro bundler ociasionally not connecting to device

### ISSUE THREAD

**Issue by aurimasmi** [flexn-io/renative#1020]
**Describe the bug**
If there is device connected an example android phone and we wan't to run it in debug mode via `npx rnv run -p android -d` rnv occasionally assumes that your host machine ip is very different than real and device can't find bundler. Usually what I do in this situation just go to AppDelegate.swift or MainApplication.kt and add man correct ip manually

**To Reproduce**
It does not happen all the time, but when it does repro steps simple

1. Connect device an example android phone
2. Run `npx rnv run -p android -d`

**Expected behavior**
App runs

**Desktop (please complete the following information):**

-   OS: osx
-   Node Version v16.18.0
-   RNV Version 0.37.0-canary.11

**Comment by mihaiblaga89** [comment]
was not able to replicate this with `1.0.0-rc.0`. Both android and ios devices seem to run just fine. Tested with harness app. Small quirk on ios, if you want to run it from xcode you'll need to start renative packager on port 8081 with `npx rnv start -p ios --port 8081`. For now this is the quickest option to get it running there for now.
