### ISSUE TITLE
Rnv assumes there is no android emulators created even if there is

### ISSUE THREAD

**Issue by aurimasmi** [flexn-io/renative#1021]
**Describe the bug**
If you have app opened and want to re-run it, rnv thinks that there is no android/androidtv emulators created and instead of re running it offers to create new device.

**To Reproduce**

1. Open your app with emulator(android/androidtv) `npx rnv run -p android`
2. Kill rnv command in cli
3. Run again  `npx rnv run -p android`

**Expected behavior**
App run fine

Screenshots:
![CleanShot2023-06-20at09 17 52](https://github.com/flexn-io/renative/assets/16107073/1568bfff-ec8e-4821-ad35-1ee441c2c691)

**Desktop (please complete the following information):**

-   OS: osx
-   Node Version v16.18.0
-   RNV Version 0.37.0-canary.11

**Comment by GabrieleKaceviciute** [comment]
It works on 1.0.0-canary.8
