### ISSUE TITLE
Rnv can't open app on ios simulator >= 15

### ISSUE THREAD

**Issue by aurimasmi** [flexn-io/renative#1023]
**Describe the bug**
Rnv can't open app on ios simulator >= 15. App is build sucesfully but on the step when it needs to be installed and opened bundler just stucks

**To Reproduce**
Try to open any ios/tvos app on simulator which has version >= 15.0

**Expected behavior**
App runs

**Screenshots or copy&paste**
![Screenshot 2023-06-20 at 09 29 02](https://github.com/flexn-io/renative/assets/16107073/28de3b94-c790-4834-8706-900ed9664b50)

**Desktop (please complete the following information):**

-   OS: osx
-   Node Version v16.18.0
-   RNV Version 0.37.0-canary.11

**Comment by mihaiblaga89** [comment]
this should already be fixed in 1.0.0+
