### ISSUE TITLE
If there is androidtv connected, you can't run on emulator anymore

### ISSUE THREAD

**Issue by aurimasmi** [flexn-io/renative#1025]
**Describe the bug**
Mostly observed on androidtv. If you managed to connect android tv device, but still decide to run your app on emulator weird things start happening. Even if in cli you write `npx rnv run -p androidtv` which should run app on emulator rnv offers one of existing emulator you choose emulator, but eventually app is being run on device.. Only way to run it on emulator is disconnect device

**To Reproduce**

1. Connect androidtv device
2. Try to run your app on emulator while tv is being connected and adb shows it

**Expected behavior**
App run fine on emulator and device whatever developer prefer 

**Desktop (please complete the following information):**

-   OS: osx
-   Node Version v16.18.0
-   RNV Version 0.37.0-canary.11

**Comment by mihaiblaga89** [comment]
supported android flags and params, with regards to device management.
`-p android -t` - ask 
`-p android`
`-p android -d` - filter only devices
`-p android -d -t` - ask from devices
`-p android -t IP:port` 
`-p android -t emu-name`
`-p android -d -t device-name` 
`-p android -t device-name`
