### ISSUE TITLE
Can't kill rnv command

### ISSUE THREAD

**Issue by aurimasmi** [flexn-io/renative#1026]
**Describe the bug**
Can't kill rnv command in terminal. If you have rnv command running(any platform basic `npx rnv run ...` command sometimes if you want to cancel in terminal it's not possible seems like it's freeze and only way to kill it is close terminal window

**To Reproduce**
Unfortunately it's not happening all the time, but the way you can try to reproduce it as I described above, try to run any platform let it fully finish and try to kill it 

**Expected behavior**
You can kill command anytime you want

**Desktop (please complete the following information):**
OS: osx
Node Version v16.18.0
RNV Version 0.37.0-canary.11

**Comment by pauliusguzas** [comment]
haven't reproduced on 1.0.0-rc.3
