### ISSUE TITLE
Can't run apps with xcode 14.3 and current rnv suported react-native version

### ISSUE THREAD

**Issue by aurimasmi** [flexn-io/renative#1027]
**Describe the bug**
ios and tvos apps is not compatible anymore with xcode 14.3

**To Reproduce**

1. Create any new rnv application
2. Install xcode 14.3
3. Try to run it

**Expected behavior**
App can run

**Desktop (please complete the following information):**

-   OS: [e.g. osx, windows 7, ubuntu 16.04]
-   Node Version [e.g. v10.16.3]
-   RNV Version 0.37.0-canary.11

**Comment by mihaiblaga89** [comment]
@ElenaDiachenko please test latest main with 14.3 and also 15. 
@mihaiblaga89 @pavjacko  we'll need to bump RN to 72.5 to include some xcode15 fixes

**Comment by ElenaDiachenko** [comment]
1.0.0-canary.0:
- ios works with different versions of xcode, tested 14.2, 14.3, 15.0.

**Comment by pauliusguzas** [comment]
@aurimasmi "Create any new rnv application" - must this be tested with new application?

**Comment by aurimasmi** [comment]
Not necessary, any existing application is also fine
