### ISSUE TITLE
Created custom carousel modular page using renative and spatial navigation but it is taking 5 to 7 seconds to switch focus, cards data is being fetch by api

### ISSUE THREAD

**Issue by komal-rana-us** [flexn-io/renative#1036]
## Issue Description:**
I have created a custom carousel for Tizen/WebOS TV, but I'm experiencing a significant delay (5 to 7 minutes) when switching focus between items. It seems that the focus switching process is taking an unusually long time.

## Steps to Reproduce:**
1. Create a custom carousel component for Tizen/WebOS TV.
2. Set up multiple items within the carousel.
3. Attempt to switch focus between the items.
4. Observe the delay in focus switching.

## Expected Behavior:**
The focus switching should occur smoothly and without significant delays.

## Actual Behavior:**
Facing delay in focusing items.

## Additional Information:**
- Version of Tizen TV platform: 6.5
- Version of WebOS TV platform: 8.0
- Steps taken to optimize the focus switching: [changed some code base to use static image as well.]

## Environment:**
- ReNative version: "0.36.1"
- Spatial navigation library/version: "2.12.9" (@noriginmedia/react-spatial-navigation)

Any insights or guidance on resolving this issue or working demo of modular page would be greatly appreciated. Thank you!

**Comment by harshmungara99** [comment]
@pavjacko @mihaiblaga89 Same issue happening with Webos latest & old sdk both. Please suggest any way to resolve such issues. We've developed our whole app through the simulator and it was working fine in it. Issue persisting in real TV devices. Hoping for support from renative team.

**Comment by krunalbadamicappital** [comment]
I am using Mac M1. Same issue happening with me as well.

**Comment by pauliusguzas** [comment]
@komal-rana-us thanks for reporting this issue, this will be looked into

**Comment by komal-rana-us** [comment]
@pauliusguzas  Any update here?

**Comment by pauliusguzas** [comment]
@komal-rana-us  @harshmungara99 sorry for late reply, these issues should be solved on latest rnv rc's (1.0.0-rc.18 being the latest)

**Comment by GabrieleKaceviciute** [comment]
Closing as answer has been provided, feel free to reopen if needed
