### ISSUE TITLE
Check what other packages can be updated on Renative

### ISSUE THREAD

**Issue by mihaiblaga89** [flexn-io/renative#1045]
Bring whatever we can up to date (packages without breaking changes)

**Comment by pavjacko** [comment]
I've updated majority runtime/dev deps including cleanup of old ones during TS refactoring. highlights:

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-1fcae48a-7fff-65f8-59e1-673a1452a1a7">
  | Current Version (0.37.3) | New Version (1.0.0)
-- | -- | --
Required Resolution Overrides | 16 | 0
Full API Documentation | NO | YES
TS Codebase | NO | YES
Security Audit | 166 Moderate \| 8 High \| 3 Critical | 4 Moderate \| 1 High
Node Support | v16 | v18
NextJS | 12.1.6 | 13.5.2
Typescript | 4.9.5 | 5.2.2
React Native | 0.67.2 | 0.72.0
Electron | 19.0.4 | 26.2.1
RN tvOS | 0.66.3 | 0.72.4-0
RN Web | 0.18.0 | 0.19.8
Lightning SDK | 5.2.0 | 5.4.1

</b>
