### ISSUE TITLE
[fireTV, tvOS] Template starter has badly styled app icon

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1059]
**Describe the bug**
Template starter has badly styled app icon

**To Reproduce**

1. Install app on device
2. Navigate to device home page to see all apps

**Expected behavior**
App icon is styled properly

**Screenshots or copy&paste**
FireTV current icon
![image](https://github.com/flexn-io/renative/assets/65670660/0e9e52ab-b9fa-43d7-93b1-2680575352f3)

tvOS current icon:
![tvos_icon](https://github.com/flexn-io/renative/assets/106537292/ada3de5e-7c60-4e19-8abe-98dab10062b5)

**Desktop (please complete the following information):**

-   OS: macOS Monterey 12.6
-   Node Version: 16.14.2
-   RNV Version: 0.37.3-rc.1

**Comment by GabrieleKaceviciute** [comment]
@rnv/template-starter: 0.38.0-canary.1

- [ ] AndroidTV current icon:
![aTV](https://github.com/flexn-io/renative/assets/106537292/db837957-21dd-4d10-a4ef-d34319a728c2)

**Comment by pauliusguzas** [comment]
1.0.0-rc.7
Atv device:
![image](https://github.com/flexn-io/renative/assets/65670660/da1a3ff1-ceae-43e7-8285-f0c3e22c9bbe)
Atv sim:
![image](https://github.com/flexn-io/renative/assets/65670660/24e91ced-3ad8-4fd7-bb46-67b114acb837)
tvOS sim:
<img width="284" alt="Screenshot 2023-12-22 at 16 34 08" src="https://github.com/flexn-io/renative/assets/65670660/796f73e0-eb7f-4da1-9e05-a2a1fdfdad66">
tvOS device:
<img width="180" alt="Screenshot 2023-12-22 at 17 24 36" src="https://github.com/flexn-io/renative/assets/65670660/26866bd2-8435-4c9a-a300-fe104f55e696">
fireTV device:
![image](https://github.com/flexn-io/renative/assets/65670660/a44d1fb9-7c49-489e-8f77-f871d6d752db)

**Comment by pauliusguzas** [comment]
rc.10
all platfroms fixed accept for firetv
![image](https://github.com/flexn-io/renative/assets/65670660/6b7c7d93-8748-42e8-90db-b9485d49c911)

**Comment by pauliusguzas** [comment]
https://stackoverflow.com/questions/58962060/how-to-set-the-fire-tv-icon-on-home-screen/59364135#59364135
https://developer.amazon.com/docs/app-submission/appstore-details.html#images-and-videos
based on those links marking as ready for release
