### ISSUE TITLE
Error while creating new project

### ISSUE THREAD

**Issue by IgoP02** [flexn-io/renative#1063]
**Describe the bug**
Trying to create a new project using `rnv new` throws the following error:
`
[ error ] [new] npm add @rnv/template-starter@0.37.0-canary.13 : FAILED. this could happen if you have package.json accidentally created somewhere in parent directory`

**To Reproduce**

1. Run `rnv new` or `npx rnv new`
2. Follow installation instructions
3. See error

**Expected behavior**
Project should be created.

**Screenshots or copy&paste**

```
? What's your project Name? (no spaces, folder based on ID will be created in this directory) s
? What's your project Title? Hello Renative
? What's your App ID? com.mycompany.s
? What's your Version? 0.1.0
? What workspace to use? rnv
[ task ] [new] loadPluginTemplates[2]
[ task ] [new] _parsePluginTemplateDependencies[2] scope:root
[ task ] [new] parseRenativeConfigs[2]
[ task ] [new] getWorkspaceDirPath[2]
? What template to use? @rnv/template-starter - Multiplatform starter kit
✔ Executing: npm view @rnv/template-starter versions
✔ Executing: npm dist-tag ls @rnv/template-starter
? What @rnv/template-starter version to use? 0.37.0-canary.13
✔ Executing: npm add @rnv/template-starter@0.37.0-canary.13
[ error ] [new] npm add @rnv/template-starter@0.37.0-canary.13 : FAILED. this could happen if you have package.json accidentally created somewhere in parent directory
[ task ] <= new

 $ rnv new - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 7/3/2023, 7:46:37 PM                                          │
│  $ rnv new                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.36.1                                                    │
│  Engine: engine-core                                                         │
│  Build Scheme (-s): debug                                                    │
│  Env Info: linux | x64 | node v20.1.0                                        │
│  Executed Time: 0h:0m:27s:149ms                                              │
│                                                                              │
│ [ error ] [new] npm add @rnv/template-starter@0.37.0-canary.13 : FAILED. this could happen if you have package.json accidentally created somewhere in parent directory
```

**Desktop:**

-   OS: Linux Mint 20.1
-   Node Version 20.1.0
-   RNV Version 0.36.1

**Additional context**
Selecting a template-starter version and continuing the installation creates a package.json and lock file in my home directory, as seen in https://github.com/flexn-io/renative/issues/922. Deleting the files and running `rnv new` again doesn't resolve the issue.

**Comment by GabrieleKaceviciute** [comment]
@IgoP02  Thanks for reporting this issue, it will be checked

**Comment by pauliusguzas** [comment]
@IgoP02 Thanks for the ticket, though I don't this this is an actual issue. If as you are saying rnv `creates a package.json and lock file in my home directory` then that means you are trying to create your project in home directory which rnv doesn't like and it says so in the error. Solution would be to navigate somewhere beside home directory and create new project there (be sure that home directory has no package.json)

**Comment by IgoP02** [comment]
No, I'm running the installer in /home/user/Projects/Project directory. Not sure why that file is being created back in the home directory in the first place.

**Comment by ahwelgemoed** [comment]
@IgoP02 - I had the same issue.

For some reason, the error occurred cause I had a rouge `package.json` file.

From what I found if I was creating the project in lets say `~/USER/NAME/Documents/projects/renative-test` if there is a `package.json` in the root of any of those folders you get this error.

In my case, there was a `package.json` in `~/USER/NAME/Documents/projects` that was not meant to be there. Once I deleted that all was good with the initial setup

**Comment by pauliusguzas** [comment]
@IgoP02 can you check above?

**Comment by pauliusguzas** [comment]
Closing as solution has been provided, please reopen if issue persists

**Comment by hemko2020** [comment]
this issue not really resolve because i facing the same issue when i create a new project in folder on my desktop package.json is create on home directory (MacOs Sonoma) i delete package.json and i recreate a new project i facing the same issue.

**Comment by hemko2020** [comment]
i used 0.37.4 that is result,

✔ Executing: npm view @rnv/template-starter versions
✔ Executing: npm dist-tag ls @rnv/template-starter
? What @rnv/template-starter version to use? 1.0.0-rc.12 (HEAD: next)
✔ Executing: yarn add @rnv/template-starter@1.0.0-rc.12
[ error ] [new] yarn add @rnv/template-starter@1.0.0-rc.12 : FAILED. this could happen if you have package.json accidentally created somewhere in parent directory
[ task ] <= new

 $ rnv start - Done! 🚀

 and my rnv version here

                                                                        │
│        Version: 0.37.4                                                       │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv start                                                           │
│        Start Time: 20/03/2024 14:04:44

**Comment by hemko2020** [comment]
@pauliusguzas it's work now when i used this template 

[Project Template: @rnv/template-starter@1.0.0-feat-bonanza.12 ]

**Comment by hemko2020** [comment]
@pauliusguzas Hi I facing this issue again and I don't why I remove the file in parent directory I create a new project but facing the issue. I'm on rnv@1.0.0-rc.12
<img width="1173" alt="Screenshot 2024-04-02 at 11 48 22" src="https://github.com/flexn-io/renative/assets/73950898/7eecb21a-6e62-4dee-919a-e05209a5f1aa">
