### ISSUE TITLE
[iOS, tvOS] Rnv doesn't recognize device by ip

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1064]
**Describe the bug**
Rnv doesn't recognize device by ip, it says that xcode doesn't support that version, however on same device using -d flag works

**To Reproduce**

1. Install rnv@0.37.0-rc.9 with yarn globally
2. Create new project with rnv new and choose rnv/template-starter with same version
3. Do `rnv run -p ios -t <IP>` or `rnv run -p tvos -t <IP>`

**Expected behavior**
App is built and installed to device

**Screenshots or copy&paste**
![Screenshot 2023-07-04 at 16 18 18](https://github.com/flexn-io/renative/assets/106537292/f234c9a0-a67b-40f9-b6e0-1c473d3ab40e)

**Desktop (please complete the following information):**

-   OS: macOS Monterey 12.6
-   Node Version 16.4.2
-   RNV Version 0.37.0-rc.9
***
-   OS: macOS Big Sur 11.6
-   Node Version 18.14.2
-   RNV Version 1.0.0-canary.7

**Comment by mihaiblaga89** [comment]
That's because xcode does not report device ips, only name/UDID so there's no way to use the `-t` as ip. It should work if you pass the name instead. Closing this as not planned
