### ISSUE TITLE
Project doesn't run on tvOS

### ISSUE THREAD

**Issue by piotr-s-nowak** [flexn-io/renative#1068]
**Describe the bug**
Hi I'm trying to run my project on the tvOS for the first time. But when I'm entering the command rnv run -p tvOS everything goes like it should up to the point where after the task checkLockAndExec. I get the error and the run stops (error message pasted in  **Screenshots or copy&paste**)

**To Reproduce**
1. Run command "rnv run -p tvOS"
2. error occurs

**Expected behavior**
Project runs as expected

**Screenshots or copy&paste**

error: unknown option `--project-path'

Command failed with exit code 1: node /Users/metroport/WebstormProjects/middleware-react/node_modules/react-native-tvos/local-cli/cli.js run-ios --project-path platformBuilds/app_tvos --scheme RNVAppTVOS --configuration Debug --simulator Apple TV --allowProvisioningUpdates
error: unknown option `--project-path'

**Desktop (please complete the following information):**

-   OS: macOS v13.4
-   Node Version v16.13.0
-   RNV Version v0.36.0

**Comment by pauliusguzas** [comment]
@piotr-s-nowak Hello, thanks for reporting this issue, could you please try [0.37.1](https://www.npmjs.com/package/rnv/v/0.37.1) version?

**Comment by piotr-s-nowak** [comment]
> @piotr-s-nowak Hello, thanks for reporting this issue, could you please try [0.37.1](https://www.npmjs.com/package/rnv/v/0.37.1) version?

@pauliusguzas unfortunately, it behaves same with [0.37.1] version

**Comment by pauliusguzas** [comment]
@piotr-s-nowak what version of xcode are you using?

**Comment by piotr-s-nowak** [comment]
@pauliusguzas I tried running it with version 14.3.1 and 14.0

**Comment by pauliusguzas** [comment]
@piotr-s-nowak hello again, could you please try 0.37.3?

**Comment by GabrieleKaceviciute** [comment]
Closing as answer has been provided
