### ISSUE TITLE
Peer Deps and New Project.

### ISSUE THREAD

**Issue by ahwelgemoed** [flexn-io/renative#1085]
**Describe the bug**
I am unable to set up a new project/app. Over the last few days I've had numerous errors and issues just to get the project running, I believe I might be doing something wrong, but I've exhausted all the available documentation. On both my m1 and intel mac, I can run normal RN Expo Apps on Android and iOs

**To Reproduce**

1. npm install rnv -g
2. Follow the steps in screenshot
3.![Screenshot 2023-08-12 at 09 26 39](https://github.com/flexn-io/renative/assets/29273599/12a13506-3a1d-4d6f-8c7d-2ce6c8e52c4a)
4. cd rng
5. code .
6. npx rnv run -p ios

**Expected behavior**
I get a long error from `npm install` mentioning `Could not resolve dependency: peer react@"17.0.2" from react-native@0.67.2`

**Screenshots or copy&paste**
![Screenshot 2023-08-12 at 09 29 03](https://github.com/flexn-io/renative/assets/29273599/c7d285f7-2a78-4022-b8f0-1a94a84d45db)
![Screenshot 2023-08-12 at 09 29 16](https://github.com/flexn-io/renative/assets/29273599/3f03354a-66fb-4700-95d6-dd4a20b8c5cc)

**Desktop (please complete the following information):**

-   OS: macOS Ventura (2017 Intel) but I had the same on my M1 Pro
-   Node Version: This example was run with `16.17.1` but I've had the same with 18 and 20
-   RNV Version `0.37.2` but again same with `0.37.1` and some other random versions

**Additional context**
I used ReNative a few years back with great success, and am keep to use it again, but for a few days now, I've tried to set up a simple project using ReNative on my m1 pro and intel mac with no success.

I'm very excited to start my new project and will greatly appreciate any help to get up and running

**Comment by arulkumararul2000** [comment]
@ahwelgemoed For me `npm install --force` i manually install that node modules by using this code run on terminal.

**Comment by mendoza** [comment]
Try using yarn, it's been easier for me.

**Comment by GabrieleKaceviciute** [comment]
@ahwelgemoed thanks for reporting this issue. I can't reproduce it on version 0.37.3 (macOS Monterey 12.6, Node version 16.14.2). Please update version and try again.

**Comment by pauliusguzas** [comment]
@ahwelgemoed try using yarn, node version 16.14.2, and if that doesn't help try solutions from above. If issue persists please reopen ticket

**Comment by ahwelgemoed** [comment]
Sorry for the late reply, yes using yarn and node version 16 fixed the issue for me.
I appreciate the help!
