### ISSUE TITLE
Cannot build release for android in 0.37.1

### ISSUE THREAD

**Issue by maciejsiiminski** [flexn-io/renative#1086]
**Describe the bug**
When I run command run/build -p android -s release debug apk is generated instead of release one. Command for sure works correctly for androidtv but not android. It worked correctly in 0.36.0.

**To Reproduce**
Run command run/build -p android -s release

**Expected behavior**
Release apk should be built.

**Screenshots or copy&paste**
![image](https://github.com/flexn-io/renative/assets/109077092/21fa94fe-3621-4d9e-aa28-b8de907a50a8)

**Desktop (please complete the following information):**

-   OS: windows 10
-   Node Version v16.13.0
-   RNV Version 0.37.1

**Comment by pauliusguzas** [comment]
@maciejsiiminski thanks for reporting this, PR with the fix has already been created https://github.com/flexn-io/renative/pull/1091

**Comment by pauliusguzas** [comment]
@maciejsiiminski not sure though when the release will be made so in the meanwhile you can just use production scheme for Android, on that version it it same as release in other
