### ISSUE TITLE
White screen Issue for Samsung Tizen App with ReNative v0.37.3

### ISSUE THREAD

**Issue by saumilshahdct** [flexn-io/renative#1087]
**Describe the bug:**
- I can't get my Samsung Tizen app to work on my Samsung TV 7 series. I'm using ReNative v0.37.3. The app only shows a white screen when I try to open it

**Additional context**
- I have tried multiple things to resolve this issue but I am not able to.
- I can also see "globalThis" error in console while I debug using chrome inspector (I have attached screenshot for the same).

**Steps to reproduce the behaviour:**
- create a new project with Template_Starter (Hello World Template)
`rnv new`
- Run build on Tizen TV with following command 
`rnv run -p tizen -d <<TV_IP>>`
- Observe white screen on Samsung Tizen TV

**Actual / Current behaviour:**
- Able to see White Screen

**Expected behaviour:**
- Able to see Hello World Home Page

**System:**

-   OS: MacOS 13.5
-   Node Version: v16.17.0
-   RNV Version: v0.37.3

Attachment:
![1](https://github.com/flexn-io/renative/assets/92943552/05cbbc96-dade-4c00-9be9-b458e6e4d345)

**Comment by pauliusguzas** [comment]
Duplicate to https://github.com/flexn-io/renative/issues/925
