### ISSUE TITLE
TextEncoder is not defined

### ISSUE THREAD

**Issue by cakecoke** [flexn-io/renative#1088]
**Describe the bug**
Installed new project with suggested node version getting error "TextEncoder is not defined"

**To Reproduce**

1. install app from example template
2. rnv run -p web

**Expected behavior**
server will run normally 

**Screenshots or copy&paste**
`
FAILED with ERROR: 

Command failed with exit code 1: npx next dev --port 8080

Error: Command failed with exit code 1: npx next dev --port 8080
    at makeError (/Users/mike/WebstormProjects/arax2/arax/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/mike/WebstormProjects/arax2/arax/node_modules/execa/index.js:118:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

npx next dev --port 8080 

`TextEncoder is not defined
`
**Desktop (please complete the following information):**

-   OS:  macOS 13.4.1 (c) (22F770820d)
-   node  v10.13.0
-   rnv 0.37.3

**Additional context**

**Comment by pauliusguzas** [comment]
@cakecoke closing this ticket as solution was provided, please reopen if issue persists
