### ISSUE TITLE
yarn add failed

### ISSUE THREAD

**Issue by antalmate12** [flexn-io/renative#1095]
? What's your project Name? (no spaces, folder based on ID will be created in this directory) tesssssst
? What's your project Title? Hello Renative
? What's your App ID? com.mycompany.tesssssst
? What's your Version? 0.1.0
? What workspace to use? rnv
[ task ] [new] loadPluginTemplates[2]
[ task ] [new] _parsePluginTemplateDependencies[2] scope:root
[ task ] [new] parseRenativeConfigs[2]
[ task ] [new] getWorkspaceDirPath[2]
? What template to use? @rnv/template-starter - Multiplatform 'hello world' template
✔ Executing: npm view @rnv/template-starter versions
✔ Executing: npm dist-tag ls @rnv/template-starter
? What @rnv/template-starter version to use? 0.37.3 (HEAD: latest)
✔ Executing: yarn add @rnv/template-starter@0.37.3
[ error ] [new] yarn add @rnv/template-starter@0.37.3 : FAILED. this could happen if you have package.json accidentally created somewhere in parent directory
[ task ] <= new

 $ rnv new - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 2023. 08. 30. 22:11:01                                        │
│  $ rnv new                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.3                                                    │
│  Engine: engine-core                                                         │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | x64 | node v16.20.2                                      │
│  Executed Time: 0h:0m:33s:971ms                                              │
│                                                                              │
│ [ error ] [new] yarn add @rnv/template-starter@0.37.3 : FAILED. this could happen if you have package.json accidentally created somewhere in parent directory
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

What could cause this error? I just installed rnv on my Mac, and I can't seem to create a new project. I get his error message always, and the created folder is empty.

**Comment by vvsamin** [comment]
I had the same problem with yarn.
Disable yarn and create project via npm.

`corepack disable`
`npx rnv new`

Get ready to have dependency installation errors while running _npm install_ on your first _rnv run_
After each such error, you will need to run npm install with the flag
`npm install --legacy-peer-deps`
And repeat the _rnv run_

**Comment by pauliusguzas** [comment]
@antalmate12 thanks for reporting this issue, see comments in [this](https://github.com/flexn-io/renative/issues/1063) ticket for an answer

**Comment by GabrieleKaceviciute** [comment]
Closing as answer has been provided
