### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'transformFile')

### ISSUE THREAD

**Issue by joshuaben** [flexn-io/renative#1102]
via:
`rnv run -p androidtv`

builds successfully but when selecting the app in the emulator, it fails with:

> [ task ] registerEngine:engine-core[1]
> [ task ] configureRuntimeDefaults[1] appId:null
> [ task ] checkAndMigrateProject[1]
> [ task ] loadPluginTemplates[1]
> [ task ] _parsePluginTemplateDependencies[1] scope:root
> [ task ] parseRenativeConfigs[1]
> [ task ] getWorkspaceDirPath[1]
> [ task ] _generatePlatformTemplatePaths[1]
> [ task ] checkAndBootstrapIfRequired[1]
> [ task ] loadIntegrations[1]
> [ task ] loadEngines[1]
> [ task ] loadEnginePluginDeps[1]
> [ task ] loadEnginePackageDeps[1]
> [ task ] findSuitableTask[1]
> [ info ] Current Engine: engine-core path: undefined
> [ task ] registerMissingPlatformEngines[1]
> [ task ] initializeTask[1] status
> [ task ] => [status]
> [ task ] <= status

>   ReNative Version: 0.37.3                                                    
>   Project Name ($package.name): xxxx-xptv                         
>   Project Version ($package.version): 0.1.0                                   
>   Workspace ($.workspaceID): rnv                                              
>   Platform (-p): androidtv                                                    
>   Engine ($.platforms.androidtv.engine): engine-rn-tvos                       
>   Template: @rnv/template-starter@0.38.0-canary.1                             
>   App Config (-c): app                                                        
>   Build Scheme (-s): debug                                                    
>   Target (-t): Android_TV_720p_API_22                                         
>   Supported Platforms: androidtv                                              
>   Env Info: darwin | arm64 | node v19.6.0                                     
>   Executed Time: 0h:0m:13s:92ms                                               
>                                                                              
>   All good as 🦄                                                              
>                                                                               
>   Project location:                                                           
>   ./platformBuilds/app_androidtv   

   

> error: TypeError: Cannot read properties of undefined (reading 'transformFile')
>     at Bundler.transformFile (/xxxx-xptv/node_modules/metro/src/Bundler.js:48:30)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at Object.transform (/xxxx-xptv/node_modules/metro/src/lib/transformHelpers.js:101:12)
>     at processModule (/xxxx-xptv/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:18)
>     at traverseDependenciesForSingleFile (/xxxx-xptv/node_modules/metro/src/DeltaBundler/traverseDependencies.js:131:3)
>     at async Promise.all (index 0)
>     at initialTraverseDependencies (/xxxx-xptv/node_modules/metro/src/DeltaBundler/traverseDependencies.js:114:3)
>     at DeltaCalculator._getChangedDependencies (/xxxx-xptv/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:164:25)
>     at DeltaCalculator.getDelta (/xxxx-xptv/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:94:16)
>     at DeltaBundler.buildGraph (/xxxx-xptv/node_modules/metro/src/DeltaBundler.js:50:5)
>  BUNDLE  ./index.js 

screenshot of the error:
![Screenshot 2023-09-11 at 12 18 55 PM](https://github.com/flexn-io/renative/assets/135044379/97618a6f-0c38-444c-bbeb-0757f0394d4c)

**Comment by pauliusguzas** [comment]
@joshuaben thanks for reporting this, could you try using node 16.14.2 and template 0.37.3?

**Comment by pauliusguzas** [comment]
Closing as no answer has been provided, feel free to reopen again
