### ISSUE TITLE
React Native New Architecture Roadmap?

### ISSUE THREAD

**Issue by perqa** [flexn-io/renative#1108]
Hello, 

Just wondering about support fort react-native new architecture? Is it on the roadmap? I saw that renative uses "react-native-tvos": "0.66.3-1". Even though react-native-tvos now supports the new architecture, I guess one can't just replace 0.66.3 with 0.72.4 and expect it to work... 

Best Regards, Per

**Comment by mihaiblaga89** [comment]
hey @perqa! we're currently updating to RN 72.4 as we speak. You can check the progress on this PR https://github.com/flexn-io/renative/pull/1104
