### ISSUE TITLE
showing white screen while running the app  

### ISSUE THREAD

**Issue by BhanuMathurthi** [flexn-io/renative#1109]
after running the Renative app on LG WebOS TV, the app is running but there is a white screen, and also while inspecting there is no HTML at all

after installing the packaged ipk file on LG TV, the app was installed with the title and logo but when I launched the app, it did not display anything, and also in the root element of HTML, there is no content at all in the body, i did not get what is happening

**Comment by pauliusguzas** [comment]
@BhanuMathurthi  thanks for reporting this, this is known as is being pushed to be fixed, closing as there is a ticket for this already https://github.com/flexn-io/renative/issues/925. You are welcome to add any extra information there

**Comment by BhanuMathurthi** [comment]
but i am getting this error in lg webos tv device sir, #925 is about tizen device sir

**Comment by pauliusguzas** [comment]
@BhanuMathurthi yeah, that is the same bug on both TV's, will add it to ticket

**Comment by BhanuMathurthi** [comment]
but sir, where can i find its solution? 

https://github.com/flexn-io/renative/issues/1087 in this issue, i did not found the solution, can you please provide the needful solution for the above issue, please reply sir

**Comment by pauliusguzas** [comment]
@BhanuMathurthi I am sorry but there is no solution at the moment, this is rnv bug and as I said is being pushed to be fixed asap

**Comment by BhanuMathurthi** [comment]
okay, thanks for the response. but currently is there any alternative solution for the installed renative app to run on LG webos device?

**Comment by BhanuMathurthi** [comment]
yes, as you said, it is running well in the web browser but in the chromium-browser only it is not running (as in lg device)

but when can I get an update sir regarding rnv bug if you don't mind may I know if will it be pushed to be fixed at the end of this month, sir?

**Comment by pauliusguzas** [comment]
@BhanuMathurthi I might be possible this month but I doubt it as we are currently working on rn72 upgrade, I will update you when we get this working

**Comment by BhanuMathurthi** [comment]
@pauliusguzas sir can you please reply? how can i build and integrate the hybrid react app for lg webos and tizen os?

**Comment by pauliusguzas** [comment]
> okay sure sir, but I have one more query, in the previous years, has no one able to run a renative app for LG WebOS and Tizen OS? I just want to know, if yes, how they were able to integrate the app into the LG device. Thanks

It was working long time ago, but I am afraid that that technology is so outdated atm, that it's not worth to investigate what worked years ago


> @pauliusguzas sir can you please reply? how can i build and integrate the hybrid react app without using renative for lg webos and tizen os?

On this one I am not able to answer, look for an answer in Webos and Tizen SDK's
