### ISSUE TITLE
Different output on web platform and webos device

### ISSUE THREAD

**Issue by battistini01** [flexn-io/renative#1116]
### Discussed in https://github.com/flexn-io/renative/discussions/1115

<div type='discussions-op-text'>

<sup>Originally posted by **battistini01** September 29, 2023</sup>
Hi, 
I'm getting different launch result between`rnv run -p web` and `rnv run -p webos`. 
I can run without problems with first version, but no with second one.  
I'm not getting errors but the output on my webOS device is not the same of web version running on browser. ( On LG device my app shows only flexn logo png (attached) and then white page while in browser correctly shows all different contents I wrote). 
This happens with the default template @flexn/create-template-starter template too, without any change after completed the first project initialization.

Anyone can help?

Second question: is possible to launch webOS Simulator and not the old Emulator? rnv is actually searching Emulator, but my mac M1 chip is not supported (https://webostv.developer.lge.com/develop/tools/emulator-installation)

I'm using @flexn/create-template-starter template, "rnv": "0.37.3"

I'd be very thankful if someone could have a call so I can show these problems live </div>

<img width="432" alt="image" src="https://github.com/flexn-io/renative/assets/54148906/3a5475ed-b45c-4266-a52b-dd238b45cc12">

**Comment by pauliusguzas** [comment]
@battistini01 thanks for trying out Renative. First issue you reported is known and atm is on high priority to be fixed https://github.com/flexn-io/renative/issues/925. Second question - at the moment rnv doesn't support simulator and M1, but that will be fixed in upcoming rnv releases, as rnv atm is having major refactor
