### ISSUE TITLE
[webos, tizen, tizenmobile, tizenwatch] export command exits with error even though binary was generated

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1143]
**Describe the bug**
Export command exits with error even though binary was generated (sanity_1.0.0-1 tag)

**To Reproduce**
1. go to template-starter package
2. run `rnv export -p webos`

**Expected behavior**
Warning instead of error should be displayed

**Screenshots or copy&paste**
<img width="874" alt="Screenshot 2023-10-06 at 11 23 50" src="https://github.com/flexn-io/renative/assets/65670660/e56c8638-6a5f-4f79-b4ca-4426449bc54b">

**Desktop (please complete the following information):**

-   OS: Ventura 13.5.2
-   Node Version 18.16.0
-   RNV Version 1.0.0-canary.1
-   rnv/template-starter Version 1.0.0-canary.1

**Comment by GabrieleKaceviciute** [comment]
not reproduced on 1.0.0-feat-pin-cli.2
