### ISSUE TITLE
Cant Install even after running rnv build -p tizen -s release 

### ISSUE THREAD

**Issue by HatimPatwa** [flexn-io/renative#1173]
although i followed what was in issue #756

I am not able to run that .wgt file in TV or Emulator even though it works fine in development mode, i seem to notice there is no js files seen in build folder  or .wgt file.

The Emulator gives no error and when i run through the tizen studio it just says installation error p.s without any more details

could someone please address regarding this issue ,  already started a discussion thread but i thought an issue would be appropriate if someone else faces the same issue.

**Comment by pauliusguzas** [comment]
@HatimPatwa hello, thanks for using rnv, could you tell exact steps how to reproduce? including versions and so on

**Comment by HatimPatwa** [comment]
Sure @pauliusguzas 

rnv version -  0.37.3

i built it with command - rnv build -p tizen -s release

The build says success and i cant see any major warning or error. Also attaching the **app_tizen** folder build genereated.
For reference the app is quite heavy i guess, but the .wgt is only 12kb and that puts me in some thought that there is no JS file inserted when it built.

note :- The **rnv run -p tizen** works perfectly without any error and displays correctly on tizen emulator. 

app_tizen build folder- 
![image](https://github.com/flexn-io/renative/assets/63943234/dedfbc1a-76e5-428d-8aa7-3c9853c2e791)


extra note:  if you see below image the .wgt should have atleast **500kb - 1MB** size. as it says the js itself is only 458 kb .----------
![image](https://github.com/flexn-io/renative/assets/63943234/c3d9d796-8227-4d97-8a07-0edece3ee220)





log when building - 

`┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 0.37.3                                                       │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv build -p tizen -s release                                       │
│        Start Time: 10/16/2023, 11:23:23 AM                                   │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:null
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] _parsePluginTemplateDependencies[1] scope:root
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] _generatePlatformTemplatePaths[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] loadEnginePluginDeps[1]
[ task ] loadEnginePackageDeps[1]
[ task ] registerEngine:engine-rn-web[1]
[ task ] findSuitableTask[1]
[ info ] Current Engine: engine-rn-web path: ./node_modules/@rnv/engine-rn-web
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] build
[ task ] => [build]
[ task ] [build] checkIfProjectAndNodeModulesExists[1]
[ hook ] [build] executePipe ('build:before')
[ task ] [build] taskRnvBuild[1] parent:null
[ task ] => [build] => [package]
[ hook ] [package] executePipe ('package:before')
[ task ] [package] taskRnvPackage[1] parent:build
[ task ] => [package] => [configure]
[ hook ] [configure] executePipe ('configure:before')
[ task ] [configure] taskRnvConfigure[1]
[ task ] => [configure] => [platform configure]
[ hook ] [platform configure] executePipe ('platform:configure:before')
[ task ] [platform configure] taskRnvPlatformConfigure[1] 
[ task ] => [platform configure] => [project configure]
[ hook ] [project configure] executePipe ('project:configure:before')
[ task ] [project configure] taskRnvProjectConfigure[1]
[ task ] [project configure] checkAndMigrateProject[2]
[ task ] [project configure] loadPluginTemplates[2]
[ task ] [project configure] _parsePluginTemplateDependencies[2] scope:root
[ task ] [project configure] parseRenativeConfigs[2]
[ task ] [project configure] getWorkspaceDirPath[2]
[ task ] [project configure] _generatePlatformTemplatePaths[2]
[ task ] => [project configure] => [workspace configure]
[ task ] [workspace configure] taskRnvWorkspaceConfigure[1]
[ task ] <= [project configure] <= workspace configure
[ task ] [project configure] checkIfTemplateConfigured[1]
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[1] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] [project configure] checkCrypto[1]
[ task ] [project configure] configureRuntimeDefaults[2] appId:app
[ task ] [project configure] applyTemplate[1] @rnv/template-starter=>undefined
[ task ] [project configure] _applyTemplate[1] current:@rnv/template-starter selected:undefined
[ task ] [project configure] configureRuntimeDefaults[3] appId:app
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[2] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] => [project configure] => [app configure]
[ hook ] [app configure] executePipe ('app:configure:before')
[ task ] [app configure] taskRnvAppConfigure[1]
[ task ] [app configure] listAppConfigsFoldersSync[1] ignoreHiddenConfigs:true
[ task ] [app configure] loadPluginTemplates[3]
[ task ] [app configure] _parsePluginTemplateDependencies[3] scope:root
[ task ] [app configure] parseRenativeConfigs[3]
[ task ] [app configure] generateBuildConfig[1] size:193.3 KB
[ task ] [app configure] getWorkspaceDirPath[3]
[ task ] [app configure] generateBuildConfig[2] size:193.3 KB
[ task ] [app configure] generateBuildConfig[3] size:193.3 KB
[ task ] [app configure] generateBuildConfig[4] size:193.3 KB
[ task ] [app configure] _generatePlatformTemplatePaths[3]
[ task ] [app configure] generateBuildConfig[5] size:206.4 KB
[ task ] [app configure] generateBuildConfig[6] size:206.4 KB
[ task ] [app configure] getWorkspaceDirPath[4]
[ task ] [app configure] generateBuildConfig[7] size:206.4 KB
[ task ] [app configure] generateLocalConfig[1] resetAppId:false
[ task ] [app configure] generateBuildConfig[8] size:206.4 KB
[ info ] [app configure] Current App Config: app
[ hook ] [app configure] executePipe ('app:configure:after')
[ task ] <= [project configure] <= app configure
[ task ] [project configure] versionCheck[1]
[ task ] [project configure] versionCheck:rnvRunner:0.37.3,rnvProject:0.37.3[1]
[ task ] [project configure] configureEngines[1]
[ task ] [project configure] resolvePluginDependants[1]
[ task ] [project configure] configurePlugins[1]
[ task ] [project configure] configureRuntimeDefaults[4] appId:app
[ task ] [project configure] copyRuntimeAssets[1]
[ task ] [project configure] configureTemplateFiles[1]
[ task ] [project configure] checkAndCreateGitignore[1]
[ task ] [project configure] checkAndCreateBabelConfig[1]
[ task ] [project configure] generateRuntimeConfig[1]
[ task ] [project configure] overrideTemplatePlugins[1]
[ task ] [project configure] parsePlugins[1]
[ info ] [project configure] /react-native overriden by: /@flexn/plugins/pluginTemplates/react-native/overrides@0.67.2
[ info ] [project configure] /@react-native-community/cli-platform-ios overriden by: /@flexn/plugins/pluginTemplates/@react-native-community/cli-platform-ios/overrides
[ info ] [project configure] /react-native-gesture-handler overriden by: /@flexn/plugins/pluginTemplates/react-native-gesture-handler/overrides
[ task ] [project configure] parseFonts[1]
[ task ] [project configure] parsePlugins[2]
[ hook ] [project configure] executePipe ('project:configure:after')
[ task ] <= [platform configure] <= project configure
[ task ] [platform configure] isPlatformSupported[1]
[ task ] [platform configure] checkAndConfigureSdks[1]
[ task ] [platform configure] checkAndConfigureTizenSdks:tizen[1]
[ task ] [platform configure] isBuildSchemeSupported[1]
[ info ] [platform configure] Current Build Scheme: release
[ task ] [platform configure] checkSdk[1]
[ task ] [platform configure] _isSdkInstalled[1]
[ task ] [platform configure] checkAndConfigureAndroidSdks[1] (/Users/<USER>/Library/Android/sdk)
[ task ] [platform configure] configureRuntimeDefaults[5] appId:app
[ task ] => [platform configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[3] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [platform configure] <= install
[ task ] [platform configure] [1] taskRnvPlatformConfigure hasBuildFolderPresent:true
[ task ] [platform configure] createPlatformBuild[1]
[ task ] [platform configure] injectPlatformDependencies[1]
[ hook ] [platform configure] executePipe ('platform:configure:after')
[ task ] <= [configure] <= platform configure
[ task ] [configure] configureEntryPoint[1]
[ task ] [configure] copySharedPlatforms[1]
[ task ] [configure] configureTizenProject[1]
[ task ] [configure] configureTizenGlobal[1]
[ task ] [configure] copyAssetsFolder[1]
[ info ] [configure] Found custom assetSources at ./node_modules/@flexn/assets-renative-outline/assets/tizen. Will be used to generate assets.
[ task ] [configure] configureCoreWebProject[1]
[ task ] [configure] _configureProject[1]
[ task ] [configure] copyBuildsFolder[1]
[ task ] [configure] copyTemplatePluginsSync[1] (./platformBuilds/app_tizen)
[ task ] [configure] parsePlugins[1]
[ hook ] [configure] executePipe ('configure:after')
[ task ] <= [package] <= configure
[ hook ] [package] executePipe ('package:after')
[ task ] <= [build] <= package
[ task ] [build] buildTizenProject[1]
[ task ] [build] buildCoreWebpackProject[1]
[ task ] [build] parsePlugins[2]
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.

babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
  
[ success ] [build] Compiled successfully.

[ info ] [build] File sizes after gzip:

  458.84 kB  build/static/js/main.ee6d9644.js
  333 B      build/static/css/main.cf724622.css
The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The platformBuilds/app_tizen/build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

✔ Executing: /home/hatimpatwa/tizen-studio/tools/ide/bin/tizen build-web -- /home/hatimpatwa/Hatim/TVSastana/RenativeApp/sastanatv/platformBuilds/app_tizen -out /home/hatimpatwa/Hatim/TVSastana/RenativeApp/sastanatv/platformBuilds/app_tizen/build
✔ Executing: /home/hatimpatwa/tizen-studio/tools/ide/bin/tizen package -- /home/hatimpatwa/Hatim/TVSastana/RenativeApp/sastanatv/platformBuilds/app_tizen/build -s Sample -t wgt -o /home/hatimpatwa/Hatim/TVSastana/RenativeApp/sastanatv/platformBuilds/app_tizen/output
[ success ] [build] Your WGT package is located in ./platformBuilds/app_tizen/output .
[ hook ] [build] executePipe ('build:after')
[ task ] <= build

 $ rnv build -p tizen -s release - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/16/2023, 11:23:53 AM                                       │
│  $ rnv build -p tizen -s release                                             │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.3                                                    │
│  Project Name ($package.name): sastanatv                                     │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): tizen                                                        │
│  Engine ($.platforms.tizen.engine): engine-rn-web                            │
│  Template: @rnv/template-starter@0.37.3                                      │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): release                                                  │
│  Bundle assets ($.platforms.tizen.bundleAssets): true                        │
│  Target (-t): T-samsung-7.0-x86                                              │
│  Supported Platforms: tizen                                                  │
│  Env Info: linux | x64 | node v18.17.1                                       │
│  Executed Time: 0h:0m:29s:997ms                                              │
│                                                                              │
│ [ success ] [build] Compiled successfully.

│ [ success ] [build] Your WGT package is located in ./platformBuilds/app_tizen/output .
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_tizen                                                  │
└──────────────────────────────────────────────────────────────────────────────┘`




Let me know if you need anything else i am happy to provide

**Comment by HatimPatwa** [comment]
@pauliusguzas  I would really appreciate your further thought on this issue.

**Comment by pauliusguzas** [comment]
@HatimPatwa tested on 1.0.0-canary.4 which has major updates but seems like same issue remains, build generated is 12kb, but I was able to install the generated binary to real TV using tizen CLI, the TV shows screen below after installing binary
![PXL_20231017_084140159 MP](https://github.com/flexn-io/renative/assets/65670660/1e40ca92-1759-4a32-8666-e047cb8a2a57)

**Comment by HatimPatwa** [comment]
@pauliusguzas 
So the build .wgt you installed on tv, has its locals files,

could you test running a .wgt from renative basic template starter, and installing it on tv .
coz i tested a template started code too, with no code from my end that too doesnt work..

**Comment by HatimPatwa** [comment]
> @pauliusguzas So the build .wgt you installed on tv, has its local JS files,
> 
> could you test running a .wgt from renative basic template starter, and installing it on tv . coz i tested a template started code too, with no code from my end that too doesnt work..

and if possible could you share the tizen cli documentation u used to install it.ps

**Comment by pauliusguzas** [comment]
I have tested basic template starter from renative repo using 1.0.0-canary.4 version. This version doesn't work with rnv new so could't test that. And building tizen 0.37.3 on project created with rnv new based on template starter fails with specific template related bug, so that also doesn't work. haven't tested repo checkout with 0.37.3. The command which I have used is `/Users/pauliusguzas/tizen-studio/tools/ide/bin/tizen install -n path/to/your/app -t serial_number`

**Comment by HatimPatwa** [comment]
### I Feel Silly for Doing This but i got a workaround , 

after running rnv build -p tizen--
when the commands are getting executed line by line when it displays Compiled successfully , at that moment i press ctrl + C and stop execution further giving me the desired build JS files , and after that i manually package them with tizen CLI . 😆 🤣 

It actually Works

#### But Now i am happy that this issue helped in creating a fix PS 👍🏻

**Comment by pauliusguzas** [comment]
@HatimPatwa should be fixed in 1.0.0-rc.7
