### ISSUE TITLE
Build not generating for WebOS

### ISSUE THREAD

**Issue by indrajeeta** [flexn-io/renative#1174]
Hello, 

I am trying to generate build for webos (I am using renative-template-blank template) with "rnv build -p webos", but getting failed with an error  "ares-package ERR! Error: CLI: The specified path does not exist <icon.png>".

I tried creating build for tizen, and it was successfully created.

Can anybody tell me what's wrong and what steps should I take to resolve this issue.

FULL STACKTRACE - 

D:\myKlikk\MyKlikkTv>rnv build -p webos

┌──────────────────────────────────────────────────────────────────────────────┐
│
        │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│
        │
│        Version: 0.37.3
        │
│        https://renative.org
        │
│        RNV Firing up!...
        │
│        $ rnv build -p webos
        │
│        Start Time: 13/10/2023, 4:40:00 pm
        │
│
        │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:null
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] _parsePluginTemplateDependencies[1] scope:root
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] _generatePlatformTemplatePaths[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] loadEnginePluginDeps[1]
[ task ] loadEnginePackageDeps[1]
[ task ] registerEngine:engine-rn-web[1]
[ task ] findSuitableTask[1]
[ info ] Current Engine: engine-rn-web path: D:\myKlikk\MyKlikkTv\node_modules\@rnv\engine-rn-web
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] build
[ task ] => [build]
[ task ] [build] checkIfProjectAndNodeModulesExists[1]
[ hook ] [build] executePipe ('build:before')
[ task ] [build] taskRnvBuild[1] parent:null
[ task ] => [build] => [package]
[ hook ] [package] executePipe ('package:before')
[ task ] [package] taskRnvPackage[1] parent:build
[ task ] => [package] => [configure]
[ hook ] [configure] executePipe ('configure:before')
[ task ] [configure] taskRnvConfigure[1]
[ task ] => [configure] => [platform configure]
[ hook ] [platform configure] executePipe ('platform:configure:before')[ task ] [platform configure] taskRnvPlatformConfigure[1]
[ task ] => [platform configure] => [project configure]
[ hook ] [project configure] executePipe ('project:configure:before')
[ task ] [project configure] taskRnvProjectConfigure[1]
[ task ] [project configure] checkAndMigrateProject[2]
[ task ] [project configure] loadPluginTemplates[2]
[ task ] [project configure] _parsePluginTemplateDependencies[2] scope:root
[ task ] [project configure] parseRenativeConfigs[2]
[ task ] [project configure] getWorkspaceDirPath[2]
[ task ] [project configure] _generatePlatformTemplatePaths[2]
[ task ] => [project configure] => [workspace configure]
[ task ] [workspace configure] taskRnvWorkspaceConfigure[1]
[ task ] <= [project configure] <= workspace configure
[ task ] [project configure] checkIfTemplateConfigured[1]
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[1] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] [project configure] checkCrypto[1]
[ task ] [project configure] configureRuntimeDefaults[2] appId:blank
[ task ] [project configure] applyTemplate[1] renative-template-blank=>undefined
[ task ] [project configure] _applyTemplate[1] current:renative-template-blank selected:undefined
[ info ] [project configure] Your projectConfig folder D:\myKlikk\MyKlikkTv\appConfigs\base is missing! CREATING...DONE
[ task ] [project configure] configureRuntimeDefaults[3] appId:blank
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[2] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] => [project configure] => [app configure]
[ hook ] [app configure] executePipe ('app:configure:before')
[ task ] [app configure] taskRnvAppConfigure[1]
[ task ] [app configure] listAppConfigsFoldersSync[1] ignoreHiddenConfigs:true
[ task ] [app configure] loadPluginTemplates[3]
[ task ] [app configure] _parsePluginTemplateDependencies[3] scope:root[ task ] [app configure] parseRenativeConfigs[3]
[ task ] [app configure] generateBuildConfig[1] size:192.32 KB
[ task ] [app configure] getWorkspaceDirPath[3]
[ task ] [app configure] generateBuildConfig[2] size:192.32 KB
[ task ] [app configure] generateBuildConfig[3] size:192.32 KB
[ task ] [app configure] generateBuildConfig[4] size:192.32 KB
[ task ] [app configure] _generatePlatformTemplatePaths[3]
[ task ] [app configure] generateBuildConfig[5] size:194.54 KB
[ task ] [app configure] generateBuildConfig[6] size:194.54 KB
[ task ] [app configure] getWorkspaceDirPath[4]
[ task ] [app configure] generateBuildConfig[7] size:194.54 KB
[ task ] [app configure] generateLocalConfig[1] resetAppId:false
[ task ] [app configure] generateBuildConfig[8] size:194.54 KB
[ info ] [app configure] Current App Config: blank
[ hook ] [app configure] executePipe ('app:configure:after')
[ task ] <= [project configure] <= app configure
[ task ] [project configure] versionCheck[1]
[ task ] [project configure] versionCheck:rnvRunner:0.37.3,rnvProject:0.37.3[1]
[ task ] [project configure] configureEngines[1]
[ task ] [project configure] resolvePluginDependants[1]
[ task ] [project configure] configurePlugins[1]
[ task ] [project configure] configureRuntimeDefaults[4] appId:blank
[ task ] [project configure] copyRuntimeAssets[1]
[ task ] [project configure] configureTemplateFiles[1]
[ task ] [project configure] checkAndCreateGitignore[1]
[ task ] [project configure] checkAndCreateBabelConfig[1]
[ task ] [project configure] generateRuntimeConfig[1]
[ task ] [project configure] overrideTemplatePlugins[1]
[ task ] [project configure] parsePlugins[1]
[ info ] [project configure] \react-native overriden by: \@flexn\plugins\pluginTemplates\react-native\overrides@0.67.2
[ info ] [project configure] \@react-native-community\cli-platform-ios overriden by: \@flexn\plugins\pluginTemplates\@react-native-community\cli-platform-ios\overrides
[ info ] [project configure] \react-native-gesture-handler overriden by: \@flexn\plugins\pluginTemplates\react-native-gesture-handler\overrides
[ info ] [project configure] \react-native-reanimated overriden by: \@flexn\plugins\pluginTemplates\react-native-reanimated\overrides
[ info ] [project configure] \react-native-tvos overriden by: \@flexn\plugins\pluginTemplates\react-native-tvos\overrides@0.66.3-1
[ info ] [project configure] \react-native-vector-icons overriden by: \@flexn\plugins\pluginTemplates\react-native-vector-icons\overrides
[ task ] [project configure] parseFonts[1]
[ task ] [project configure] parsePlugins[2]
[ hook ] [project configure] executePipe ('project:configure:after')
[ task ] <= [platform configure] <= project configure
[ task ] [platform configure] isPlatformSupported[1]
[ task ] [platform configure] checkAndConfigureSdks[1]
[ task ] [platform configure] checkAndConfigureWebosSdks:webos[1]
[ task ] [platform configure] isBuildSchemeSupported[1]
[ info ] [platform configure] Current Build Scheme: debug
[ task ] [platform configure] checkSdk[1]
[ task ] [platform configure] _isSdkInstalled[1]
[ task ] [platform configure] checkAndConfigureAndroidSdks[1] (C:\Users\Admin\AppData\Local\Android\sdk)
[ task ] [platform configure] configureRuntimeDefaults[5] appId:blank
[ task ] => [platform configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[3] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [platform configure] <= install
[ task ] [platform configure] [1] taskRnvPlatformConfigure hasBuildFolderPresent:true
[ task ] [platform configure] createPlatformBuild[1]
[ task ] [platform configure] injectPlatformDependencies[1]
[ hook ] [platform configure] executePipe ('platform:configure:after')
[ task ] <= [configure] <= platform configure
[ task ] [configure] configureEntryPoint[1]
[ task ] [configure] copySharedPlatforms[1]
[ task ] [configure] configureWebOSProject[1]
[ task ] [configure] copyAssetsFolder[1]
[ warn ] [configure] Your app is missing assets at D:\myKlikk\MyKlikkTv\appConfigs\base,D:\myKlikk\MyKlikkTv\appConfigs\blank.
[ task ] [configure] configureCoreWebProject[1]
[ task ] [configure] _configureProject[1]
[ task ] [configure] copyBuildsFolder[1]
[ task ] [configure] copyTemplatePluginsSync[1] (D:\myKlikk\MyKlikkTv\platformBuilds\blank_webos)
[ task ] [configure] parsePlugins[1]
[ hook ] [configure] executePipe ('configure:after')
[ task ] <= [package] <= configure
[ hook ] [package] executePipe ('package:after')
[ task ] <= [build] <= package
[ task ] [build] buildWebOSProject[1]
[ task ] [build] buildCoreWebpackProject[1]
[ task ] [build] parsePlugins[2]
[ success ] [build] Compiled successfully.

[ info ] [build] File sizes after gzip:

  240.88 kB  build\static\js\main.f064b148.js
The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The platformBuilds\blank_webos\build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

× FAILED: C:\webOS_TV_SDK\CLI\bin\ares-package.cmd -o D:\myKlikk\MyKlikkTv\platformBuilds\blank_webos\output D:\myKlikk\MyKlikkTv\platformBuilds\blank_webos -n
┌──────────────────────────────────────────────────────────────────────────────┐
│  RNV  SUMMARY | 13/10/2023, 4:40:14 pm
        │
│  $ rnv build -p webos
        │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.3
        │
│  Project Name ($package.name): MyKlikkTv
        │
│  Project Version ($package.version): 0.1.0
        │
│  Workspace ($.workspaceID): rnv
        │
│  Platform (-p): webos
        │
│  Engine ($.platforms.webos.engine): engine-rn-web
        │
│  Template: renative-template-blank@0.35.4
        │
│  App Config (-c): blank
        │
│  Build Scheme (-s): debug
        │
│  Target (-t): emulator
        │
│  Supported Platforms: webos
        │
│  Env Info: win32 | x64 | node v18.18.0
        │
│  Executed Time: 0h:0m:14s:69ms
        │
│
        │
│ [ warn ] [configure] Your app is missing assets at D:\myKlikk\MyKlikkTv\appConfigs\base,D:\myKlikk\MyKlikkTv\appConfigs\blank.
│ [ success ] [build] Compiled successfully.

│ [ error ] [build] COMMAND:

C:\webOS_TV_SDK\CLI\bin\ares-package.cmd -o D:\myKlikk\MyKlikkTv\platformBuilds\blank_webos\output D:\myKlikk\MyKlikkTv\platformBuilds\blank_webos -n

FAILED with ERROR:

ares-package ERR! Error: CLI: The specified path does not exist <icon.png>

Command failed with exit code 4294967295: C:\webOS_TV_SDK\CLI\bin\ares-package.cmd -o D:\myKlikk\MyKlikkTv\platformBuilds\blank_webos\output D:\myKlikk\MyKlikkTv\platformBuilds\blank_webos -n
ares-package ERR! Error: CLI: The specified path does not exist <icon.png>

ares-package ERR! Error: CLI: The specified path does not exist <icon.png>

Error: Command failed with exit code 4294967295: C:\webOS_TV_SDK\CLI\bin\ares-package.cmd -o D:\myKlikk\MyKlikkTv\platformBuilds\blank_webos\output D:\myKlikk\MyKlikkTv\platformBuilds\blank_webos -n
ares-package ERR! Error: CLI: The specified path does not exist <icon.png>
    at makeError (D:\myKlikk\MyKlikkTv\node_modules\execa\lib\error.js:60:11)
    at handlePromise (D:\myKlikk\MyKlikkTv\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

│
        │
│  Project location:
        │
│  D:\myKlikk\MyKlikkTv\platformBuilds\blank_webos
        │
└──────────────────────────────────────────────────────────────────────────────┘

![RenativeWebOsIssue](https://github.com/flexn-io/renative/assets/131434688/72c6b02b-507e-44ed-ae5a-b3feca5a41db)

**Comment by pauliusguzas** [comment]
@indrajeeta hello, thanks for using rnv, could you check 1.0.0-canary.4? It should have this exact issue fixed (keep in mind this is canary and can have other places broken)

**Comment by pauliusguzas** [comment]
@indrajeeta @rnv/template-starter

**Comment by pauliusguzas** [comment]
@indrajeeta forgot to inform that `rnv new` doesn't work on that version, so all you can do is clone renative repo, checkout `1.0.0-canary.4` tag, do `yarn bootstrap` from root, then navigate to `packages/template starter` and run your command there

**Comment by GabrieleKaceviciute** [comment]
It works on 1.0.0-canary.8
