### ISSUE TITLE
[webos, tizen] --hosted opens web session twice (in two seperate tabs)

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1227]
**Describe the bug**
Platforms with --hosted open web session twice (in two seperate tabs)

**To Reproduce**
1. go to template-starter package
3. run `rnv run -p webos --hosted`

**Expected behavior**
One tab opens

**Desktop (please complete the following information):**

-   OS: Ventura 13.5.2 (Intel)
-   Node Version 18.16.0
-   RNV Version 1.0.0-feat-pin-cli.2
-   rnv/template-starter Version 1.0.0-feat-pin-cli.2

**Comment by ElenaDiachenko** [comment]
Can't reproduce

**Comment by pauliusguzas** [comment]
@ElenaDiachenko one browser tab opens with 0.0.0.0:port and other with 127.0.0.1:port
