### ISSUE TITLE
lerna bootstrap command removed in v7 (1.0.0-canary.7)

### ISSUE THREAD

**Issue by VMBindraban** [flexn-io/renative#1239]
**Describe the bug**
`lerna` removed the bootstrap command, this is used in the `bootstrap` script.

[A clear and concise description of what the bug is.](https://lerna.js.org/docs/legacy-package-management)

**To Reproduce**

1. Run command 'yarn run bootstrap'
2. See error

```
ERR! bootstrap The "bootstrap" command was removed by default in v7, and is no longer maintained.
ERR! bootstrap Learn more about this change at https://lerna.js.org/docs/legacy-package-management
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Note**
`npx` tried to install `lerna@7`.

**Comment by RicardasN** [comment]
@GabrieleKaceviciute I see @pavjacko changed the bootstrap code a month ago, so this issue can be closed as it should no longer be reproducable

**Comment by GabrieleKaceviciute** [comment]
@VMBindraban Closing as issue was resolved, feel free to reopen if needed.
