### ISSUE TITLE
Add support for detecting global installed packages

### ISSUE THREAD

**Issue by mihaiblaga89** [flexn-io/renative#124]
Detect problematic packages installed globally and warn the user

**Comment by maximilize** [comment]
@mihaiblaga89 Please evaluate this in more detail.

**Comment by mihaiblaga89** [comment]
Like, having webpack installed globally, caused some issues in the past. The idea was to list globally installed packages and search for packages like webpack, babel stuff, etc, and warn the user that they might cause problems. Even better, implement this in a separate command as well, like `rnv doctor` where we can add more stuff related to environment
