### ISSUE TITLE
Issue with Generating a Static WGT Package for Tizen with JS Files Included

### ISSUE THREAD

**Issue by fisarmio** [flexn-io/renative#1241]
**ReNative Version: 0.37.4
Project Name: test7
Project Version: 0.1.0
Environment Info: Windows 32 | x64 | Node v18.18.2
Build Scheme: debug**

Description:
I'm encountering an issue while trying to generate a static WGT package for a Tizen TV app using ReNative. The build process only produces a debug version with an index.html that references an external server, without including the JavaScript files in the WGT package.

This behavior is inconsistent with the expected output, where the WGT file should contain all necessary app content, including JavaScript files, to run independently on a Tizen device.

Attempts and Observations:

1. **Running in Development Mode**: The app runs and debugs fine on a real device in development mode.

2. **Building for Production**: I tried using the command rnv build -p tizen -s release, but it returned an error stating that the 'release' schema does not exist, and only 'production' is available.

3. **Community Feedback**: Based on community discussions, I understand that the development app primarily functions as an "app shell" with a simple HTML that redirects to a development machine. For production, it's suggested to use rnv export, which should bundle everything. However, this approach hasn't yielded the expected static WGT package.

4. ** #Direct Build Issue**: When attempting to install the WGT using sdb, it fails on Tizen as it cannot load server files from my local machine. The app doesn't seem to be completely bundled into the WGT file.

Queries:
How can I generate a WGT package for Tizen that includes the JavaScript files, ensuring the app is static and independent of external servers?
Is there a specific command or a step in the build process I might be missing to achieve this?
I appreciate any guidance or assistance in resolving this issue to successfully deploy the app in a production environment.

**Comment by pauliusguzas** [comment]
@fisarmio thanks for reporting this, this is a valid issue, and is already partially fixed, but no release yet made, will inform you once release has been made

**Comment by andread95** [comment]
Hi @pauliusguzas, is there any update on this? Is there no way to build a WGT package for production with JS and CSS files included as a temporary fix while waiting for the next release?

Thank you

**Comment by pauliusguzas** [comment]
@andread95 hey, this should be resolved now, try 1.0.0-rc.12
