### ISSUE TITLE
Generate index.android.bundle

### ISSUE THREAD

**Issue by VMBindraban** [flexn-io/renative#1245]
Is it possible to generate a `index.android.bundle`?
RN has a command called `bundle` but running this in the `platformBuilds/app_android` give me all kinds of errors.

**Comment by ElenaDiachenko** [comment]
@VMBindraban Hello, sorry for the late response. You cannot run the react-native command directly. In release 1.0 of renative try to run the rnv command with the --printExec flag to see the full  output ( npx rnv run -p android --printExec).Then you can run the required command by following the example.

**Comment by VMBindraban** [comment]
Thanks for the reply, we are no longer using renative. We have build are own mechanic to build android/ios/webos/tizen.
