### ISSUE TITLE
Remote Control Tizen / WebOS not working

### ISSUE THREAD

**Issue by MwareSolutons** [flexn-io/renative#127]
the remote control dpad and numeric are doing nothing is there a keyhandler that should be implemented ?

**Comment by pavjacko** [comment]
@MwareSolutons basic focus management will be added in #125 . should be released in few days

**Comment by lukutism** [comment]
dpad works fine, for other buttons please read this article: https://developer.samsung.com/tv/develop/guides/user-interaction/remote-control

**Comment by pavjacko** [comment]
@MwareSolutons basic focus support now deployed and built into hello world template.

available in `0.23.34`

![](https://github.com/pavjacko/renative/raw/master/docs/rnv_tizen.gif?raw=true)

**Comment by ahmad-crossplatform** [comment]
Hello there , 
I have tried to install the hello world template but navigation between the two buttons did not really work neither on webOS nor on web ,  with the exception of Enter button

**Comment by mihaiblaga89** [comment]
What rnv version are you using?

**Comment by ahmad-crossplatform** [comment]
0.27.5

**Comment by GabrieleKaceviciute** [comment]
1.0.0-rc.18
No focus on both webOS and Tizen devices.

related to https://github.com/flexn-io/renative/issues/869

**Comment by pauliusguzas** [comment]
Solved in 1.0.0
