### ISSUE TITLE
Implement docs search functionality

### ISSUE THREAD

**Issue by mihaiblaga89** [flexn-io/renative#1272]
- [x] create algolia free account
- [x] implement algolia api into docs

Deployed for testing:
- https://renative-docs-testing-git-feat-addsearch-flexn-io.vercel.app/

**Comment by GabrieleKaceviciute** [comment]
@mihaiblaga89 @Marius456  how should this be tested?

**Comment by pauliusguzas** [comment]
I don't think search works as expected:


1. All results seem to be bundled into one pressable component
<img width="938" alt="Screenshot 2024-01-08 at 13 37 28" src="https://github.com/flexn-io/renative/assets/65670660/20ec173c-34a3-4d9b-9781-d46b83baa88b">
2. When user enters something, found text is highlighed and there is also space added which looks weird (maybe expected?)
<img width="291" alt="Screenshot 2024-01-08 at 13 38 48" src="https://github.com/flexn-io/renative/assets/65670660/1b868114-d876-4dc1-8ed1-f5f56c009d7d">

Also after clicking on results https://renative.org/ url opens, probably expected as this is testing environment
