### ISSUE TITLE
rnv eject does not work properly

### ISSUE THREAD

**Issue by pavjacko** [flexn-io/renative#1273]
1. in renative project run `npx rnv eject -p ios` or `npx rnv eject -p android`

output structure should look like this:

<img width="288" alt="Screenshot 2024-01-02 at 12 13 24" src="https://github.com/flexn-io/renative/assets/4638697/cbc21938-16f2-4c2c-90fa-afbc2e450502">

**Comment by pauliusguzas** [comment]
@pavjacko how should this be tested??

**Comment by GabrieleKaceviciute** [comment]
android issue is tracked on https://github.com/flexn-io/renative/issues/1307

**Comment by mihaiblaga89** [comment]
1. adding `enableJetifier = true` in renative.json for an android based platform should make `gradle.properties` from platformBuilds contain `android.enableJetifier=true`. Same for enableAndroidX
2. will create a scheme in app-harness to be able to test the plugin injections
