### ISSUE TITLE
[android, androidtv] prompts to select device when it's not necessary 

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1284]
**Describe the bug**
Asks from active device, even there is only one active device connected

**To Reproduce**

1. Make sure that only one android device is connected 
2. Go to template-starter package
3. Do `npx rnv run -p android -d` 

**Expected behavior**
App is installed on active device without prompt

**Screenshots or copy&paste**
```
? What emulator would you like to start? (Use arrow keys)
❯ Pixel_3a | Phone 📱  | arch: arm64-v8a | udid: 94CAY0MERY (device)  (active)
```

**Desktop (please complete the following information):**
-   OS: macOS Ventura 13.5.2
-   Node Version 18.14.2
-   RNV Version 1.0.0-rc.2

**Comment by pavjacko** [comment]
@GabrieleKaceviciute 
Fixed behavior will look like this:

<img width="584" alt="Screenshot 2023-12-12 at 09 53 01" src="https://github.com/flexn-io/renative/assets/4638697/b2594f53-b7ae-4746-a208-617ea6826815">
