### ISSUE TITLE
Splash screen can't be customized

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1303]
**Describe the bug**
splash screen and project name can't be customized

**To Reproduce**
1. go to template-starter
2. do `npx rnv run -p android` or any other native platform
3. observe as rnv uses default rn splash screen or no splashscreen

**Expected behavior**
splash screen can be customized

**Screenshots or copy&paste**
![image](https://github.com/flexn-io/renative/assets/65670660/1f1d31ff-00e0-4dcf-b576-8ebb97e157ff)

**Desktop (please complete the following information):**

-   OS: macOS Ventura
-   Node Version 18.14.2
-   RNV Version 1.0.0-rc.3
-   rnv/template-starter Version 1.0.0-rc.3

Note:
- We'll need to check assets package if we have the splash images, otherwise we'll need to take the one from 0.37, otherwise design one

**Comment by pauliusguzas** [comment]
Android device: splash screen exists
Android simulator: splash screen exists
iOS device: splash screen exists
iOS simulator: no splash screen
https://github.com/flexn-io/renative/assets/65670660/905a0251-1d4b-4ff7-9956-75ff3ef4b078

**Comment by pavjacko** [comment]
@pauliusguzas can you reset ios sim and try again

**Comment by pauliusguzas** [comment]
ios simulator issue moved here https://github.com/flexn-io/renative/issues/1457
