### ISSUE TITLE
Ejecting android does not include @react-native-community/cli-platform-android

### ISSUE THREAD

**Issue by mihaiblaga89** [flexn-io/renative#1307]
**Describe the bug**
`npx rnv eject -p android` should produce a platformBuilds folder (the one with _eject) that can be ran. At the moment it does not include `@react-native-community/cli-platform-android`, only ios one which should't be present on android anyway. And because this module is referenced in the gradle file, it will crash on build.

**Comment by pauliusguzas** [comment]
@mihaiblaga89 how should this be tested?

**Comment by mihaiblaga89** [comment]
being able to eject an android app sucessfully. `npx rnv eject -p android`

**Comment by GabrieleKaceviciute** [comment]
1.0.0-rc.7
`npx rnv eject -p android` -> creates `cli-platform-ios` on node_modules

<img width="461" alt="and_eject" src="https://github.com/flexn-io/renative/assets/106537292/40b0d42b-3292-426d-9043-a3423c844b56">

**Comment by pauliusguzas** [comment]
on rc.10 same happens as what @GabrieleKaceviciute highlighted in comment

**Comment by pavjacko** [comment]
@ElenaDiachenko this is not relevant anymore as `rnv eject` is deprecated (migrated out of rnv into separate integration)
