### ISSUE TITLE
Automatic Android SDK detection works but fails after selecting yes

### ISSUE THREAD

**Issue by mihaiblaga89** [flexn-io/renative#1318]
**Describe the bug**
```
[ task ] [platform configure] checkAndroidSdk[1]
[ task ] [platform configure] _isSdkInstalled[1]
[ warn ] [platform configure] android requires SDK to be installed. Your SDK path in /Users/mihaiblaga/.rnv/renative.json does not exist: /Users/<USER>/Library/Android/sdk
[ task ] [platform configure] _attemptAutoFix[1]
[ success ] [platform configure] Found existing android SDK location at /Users/mihaiblaga/Library/Android/sdk
? Do you want to use it? Yes
[ task ] [platform configure] generateBuildConfig[9] size:208.72 KB
[ task ] [platform configure] checkAndConfigureAndroidSdks[2] (/Users/mihaiblaga/Library/Android/sdk)
[ task ] [platform configure] _attemptAutoFix[2]
....
[ error ] [platform configure] ENOENT: no such file or directory, lstat '21.4.7075529'
Error: ENOENT: no such file or directory, lstat '21.4.7075529'
    at Object.lstatSync (node:fs:1666:3)
    at fsLstatSync (/Users/mihaiblaga/renative/packages/core/src/system/fs.ts:34:66)
    at /Users/mihaiblaga/renative/packages/sdk-android/src/installer.ts:106:25
```

Works on a subsequent run

**To Reproduce**

1. have a wrongly configured android sdk path
2. npx rnv run -p android
3. pick yes when asked if you want to use the detected path

**Expected behavior**

**Screenshots or copy&paste**
If applicable, copy&paste the output of the command. **Run the command with `-i` to get more debugging informations**

**Desktop (please complete the following information):**

-   OS: [e.g. osx, windows 7, ubuntu 16.04]
-   Node Version [e.g. v10.16.3]
-   RNV Version [e.g. 0.25.0]

**Additional context**

**Comment by jaimeneto85** [comment]
HI, @mihaiblaga89 I error says that your renative.json  points to a folder that don't has any sdk. Coud you verify and share mor informations? Android requires that you has on your own machine the sdk, because you need to acepted the use terms and policy. 

Note: Google changes the requirements on Play Store and now your need to build at minimum on sdk 32 but target to sdk 33

**Comment by mihaiblaga89** [comment]
@jaimeneto85 that's not the point, RNV detects the SDK, points out that "hey, found an SDK in this folder, would you like to use this one?" and if you select yes then it throws the error above. Rerunning same command now works as expected so there is an issue with how the update in the config is handled right after changing the file

**Comment by GabrieleKaceviciute** [comment]
1.0.0-rc.8
@mihaiblaga89, @Marius456 
asks twice ->
```
[ warn ] [platform configure] android requires SDK to be installed. Your SDK path in /Users/gabriele/.rnv/renative.json does not exist: /Users/gabrielessss/Library/Android/sdk
[ task ] [platform configure] _attemptAutoFix[1]
[ success ] [platform configure] Found existing android SDK location at /Users/gabriele/Library/Android/sdk
? Do you want to use it? Yes
[ task ] [platform configure] generateBuildConfig[9] size:208.73 KB
[ task ] [platform configure] checkAndConfigureAndroidSdks[2] (/Users/gabriele/Library/Android/sdk)
[ task ] [platform configure] _attemptAutoFix[2]
[ success ] [platform configure] Found existing android SDK location at /Users/gabriele/Library/Android/sdk/ndk/24.0.8215888
? Do you want to use it? Yes
```
Is it expected?
