### ISSUE TITLE
How to output single JS file

### ISSUE THREAD

**Issue by saimirg** [flexn-io/renative#1353]
How do I configure renative to build and output a single JS file for Tizen and WebOS. It is currently outputting several chunk files.

**Comment by saimirg** [comment]
WE are using reac-player instead of the default one
<img width="625" alt="image" src="https://github.com/flexn-io/renative/assets/11594998/5698c34f-25be-4f2e-825d-1b87dc9d6079">

**Comment by ElenaDiachenko** [comment]
As of version 1.0.0-rc.19  you can override the default webpack configuration using webpack.config.js.

**Comment by GabrieleKaceviciute** [comment]
Closing as answer has been provided, feel free to reopen if needed
