### ISSUE TITLE
[Regression] [android, androidwear, androidtv] `-t` do not ask to select device/simulator when needed

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1367]
**Describe the bug**
E. g. `npx rnv run -p android -t` do not ask to select target if there is active at least one device or at least one simulator.

**To Reproduce**
1. Make sure that at least one android device is connected or at least one android simulator is active
2. Go to template-starter package
3. Do `npx rnv run -p android -t` ->  app is installed and launched on active device or on active simulator
4.  Do `npx rnv run -p android -d -t` ->  app is installed and launched on active device
5.  Do `npx rnv run -p android -t non_existing_sim` ->  app is installed and launched on active device or on active simulator
6. Do `npx rnv run -p android -t non_existing_device` ->  app is installed and launched on active device or on active simulator
7. Do `npx rnv run -p android -t 111.111.111.111` ->  app is installed and launched on active device or on active simulator
8. Do `npx rnv run -p android -d -t non_existing_device` ->  app is installed and launched on active device 
9. Do `npx rnv run -p android -d -t 111.111.111.111` ->  app is installed and launched on active device

**Expected behavior**
- `-p android -t` - ask from devices and sims
- `-p android -d -t` - ask from devices

**Desktop (please complete the following information):**
-   OS: macOS Ventura 13.5.2
-   Node Version 18.19.0
-   RNV Version 1.0.0-rc.10

**Comment by pauliusguzas** [comment]
`npx rnv run -p android -t nonExistingName` also installs to active sim, while it should ask to choose

**Comment by pauliusguzas** [comment]
on new project when device is connected couldn't reproduce with same rnv version
