### ISSUE TITLE
Does ReNative support windows and latest version?

### ISSUE THREAD

**Issue by JigmetAvinash** [flexn-io/renative#1374]
So I am basically a windows developer and want to build on ReNative. I use windows to develop apps. Can I make apps using ReNative. Also, how the documentation is not very good, I am having multiple errors while using running the application on android.  Need help.

**Comment by pauliusguzas** [comment]
@JigmetAvinash hello, we are currently in progress on rolling out with 1.0.0 version, you can try 1.0.0-rc.11 which is the latest release candidate. If you are facing issues on that version, please add them to this ticket

**Comment by GabrieleKaceviciute** [comment]
Closing as answer has been provided, feel free to reopen if needed.
