### ISSUE TITLE
[Windows] bootstrap-clean fails

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1399]
**Describe the bug**
bootstrap-clean script fails

**To Reproduce**
1. run `yarn bootstrap-clean`

**Expected behavior**
packages are installed 

**Screenshots or copy&paste**
```
PS C:\Users\dev\Desktop\renative> yarn bootstrap-clean
yarn run v1.22.21
$ rimraf -I ./node_modules; npx lerna clean --yes && yarn bootstrap
unknown option: --yes
run `rimraf --help` for usage information
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
**Desktop (please complete the following information):**

-   OS: Windows 10 Pro
-   Node Version 18.19.0
-   RNV Version 1.0.0-rc.11
-   rnv/template-starter Version 1.0.0-rc.11

**Comment by RicardasN** [comment]
The issue was with the `;` inside the script as it should be `&` on Windows, that cleans up the packages, however in the release 1.0 branch `bootstrap-clean` script is already changed to `yarn clean-gitignore` and the error cannot be reproduced. 

Tested on Windows 10 Pro N, Version 22H2
