### ISSUE TITLE
Request: typescript

### ISSUE THREAD

**Issue by ArThoX** [flexn-io/renative#14]
Hi

Have you ever considered migrating to typescript  ? I encounter issues trying :).

**Comment by pavjacko** [comment]
@ArThoX potentially in the future. right now the platform coverage and build system takes the priority lane. I'll keep this open to see if more people are interested!

**Comment by bdh1011** [comment]
+1!

**Comment by ahmad-crossplatform** [comment]
+1

**Comment by mi5ha** [comment]
+1

**Comment by madakk** [comment]
+1

**Comment by AngelsProjects** [comment]
+1

**Comment by pchmelar** [comment]
+1

**Comment by dluc** [comment]
+1 please!

**Comment by odemolliens** [comment]
+1!

**Comment by mihaiblaga89** [comment]
a small little update, we started migrating our source code to TS so it's coming

**Comment by odemolliens** [comment]
That's a good news!

**Comment by GabrieleKaceviciute** [comment]
Closing as issue was resolved
