### ISSUE TITLE
fix chromecast platform

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1456]
**Describe the bug**
Command `rnv run -p chromecast` in template starter folder  opens template starter web page instead of chromecast page.

**To Reproduce**

1. Go to template starter folder
2. Run command: "npx rnv run -p chromecast"
3. Go to `http://localhost:8095`

**Comment by GabrieleKaceviciute** [comment]
app-harness tested on `fix/chromecast_template_view` branch
- no available devices found on android
- nothing happens on ios
more info here -> https://github.com/flexn-io/renative/pull/1459#issuecomment-2051070086
