### ISSUE TITLE
[iOS] No splash screen on ios (device)

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1457]
**Describe the bug**
splash screen on ios simulator doens't work. On device splash screen is displayed

**To Reproduce**
1. go to app-harness
2. do `npx rnv run -p ios`
3. observe as instead of splash screen user sees black screen

**Expected behavior**
splash screen is displayed

**Screenshots or copy&paste**
https://github.com/flexn-io/renative/assets/65670660/905a0251-1d4b-4ff7-9956-75ff3ef4b078

**Desktop (please complete the following information):**
-   OS: macOS Ventura
-   Node Version 18.19.0
-   RNV Version 1.0.0-rc.12
-   rnv/app-harness Version 1.0.0-rc.12

**Comment by GabrieleKaceviciute** [comment]
v1.0.0-rc.16
No splash screen on ios device also ->
Tested on iPhone 7 Plus, OS v.15.8.1

https://github.com/flexn-io/renative/assets/106537292/6b367dd0-ad19-480b-b641-79319e2e7a84


https://github.com/flexn-io/renative/assets/106537292/900ed981-6ccd-4c3a-aabb-fb7b29c90e35
