### ISSUE TITLE
Enable e2e on apple platforms

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1466]
TODO:
update minnions

Having an issue where minion is using ruby 3.3, but when gha trigers ruby -v, minion returns 2.6 (default macos one). Wrong used ruby version makes running ios/tvos not possible

**Comment by mihaiblaga89** [comment]
should be unblocked now, both minions 5 and 6 should be running the correct version of ruby


![Image](https://github.com/flexn-io/renative/assets/4787898/766371ec-51d4-4e1a-86e0-67c2f3c91af8)
