### ISSUE TITLE
Could not resolve "@rnv/core" {TizenTv and WebOs project}

### ISSUE THREAD

**Issue by hemko2020** [flexn-io/renative#1478]
Hello i facing this issue when i run my Tizentv and WebOs project 
<img width="1015" alt="Capture d’écran 2024-03-20 à 15 24 33" src="https://github.com/flexn-io/renative/assets/73950898/a84c0c20-a473-4355-a4bd-7ac007e50b86">

somebody facing the same issue?? i need help

**Comment by hemko2020** [comment]
@pauliusguzas  is the new project  the template starter is @rnv/template-starter@1.0.0-feat-bonanza.12 for Tizen i have a real device target in wireless remote 
[ hook ] [run] buildHooks Build hooks not complied. BUILDING...
(node:34991) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 > buildHooks/src/index.js:1:24: error: Could not resolve "@rnv/core" (mark it as external to exclude it from the bundle)
    1 │ import { logHook } from '@rnv/core';
that is error i facing when i launch (rnv run cmd)

**Comment by pauliusguzas** [comment]
@hemko2020 please use 1.0.0-rc.12 for both template-starter and rnv cli itself, there are major changes in this version. If you are getting same version, please tell

**Comment by hemko2020** [comment]
ok let's try

**Comment by pauliusguzas** [comment]
@hemko2020 you have package.json file somewhere from your project directory to root

**Comment by hemko2020** [comment]
@pauliusguzas  yes i resolved this issue is good now thanks

**Comment by pauliusguzas** [comment]
@hemko2020 glad to help, if you face any more tizen or webos issues, post here

**Comment by hemko2020** [comment]
@pauliusguzas Hello i facing some issue with webOS, Tizen and android and androidtv 

Android and AndroidTv i facing a same error:
 
<img width="677" alt="Capture d’écran 2024-03-22 à 10 14 19" src="https://github.com/flexn-io/renative/assets/73950898/5b248c99-bbec-4008-8281-af7ecfdf2f7e">

Tizen tv i facing this issue :
<img width="987" alt="Capture d’écran 2024-03-22 à 10 23 51" src="https://github.com/flexn-io/renative/assets/73950898/57e2134b-4a69-495f-90be-6685b2ce06cb">

 and WebOs i have a CLI but he can't find 

<img width="980" alt="Capture d’écran 2024-03-22 à 10 25 24" src="https://github.com/flexn-io/renative/assets/73950898/011eb9c5-fd93-498d-889e-4b714f19e682">

Path is correct

<img width="771" alt="Capture d’écran 2024-03-22 à 10 26 14" src="https://github.com/flexn-io/renative/assets/73950898/0ad5da7f-f977-4a73-8065-5f4e8bd26aef">

**Comment by pauliusguzas** [comment]
Android/AndroidTV and Tizen please share whole log. Webos your path is wrong, you don't need bin/ares-package. You can tell that from this line as rnv ads bin/ares-package on top
<img width="1504" alt="Screenshot 2024-03-22 at 11 34 03" src="https://github.com/flexn-io/renative/assets/65670660/44040272-fb38-4b42-9876-03dcae361d71">

**Comment by hemko2020** [comment]
@pauliusguzas  Back ok let met try on Tizen I facing this error when I finish to create my project and I run cmd "rnv run" I'm on RC12 

[buildHooks/src/index.js:1:24: error: Could not resolve "@rnv/core" (mark it as external to exclude it from the bundle)]

**Comment by pauliusguzas** [comment]
@hemko2020 try `npx rnv run`

**Comment by hemko2020** [comment]
it's ok now I can run on Tizen tv. @pauliusguzas 
but I facing another issue with webOs I can find my simulator I don't know why?
<img width="1205" alt="Screenshot 2024-03-29 at 14 20 37" src="https://github.com/flexn-io/renative/assets/73950898/22d1a95b-8023-4316-aaf2-011948c712dd">
and I have another I try to use the second template but he doesn't work I try the latest version 1.2.0 and the top one of alpha 1.3.0 which version is good to work?

**Comment by pauliusguzas** [comment]
I see 2 issues here:
1. You are using webos emulator, renative doesn't support webos emulator, only webos simulator
2. 1.0.0-rc.12 should be used both for renative and for template-starter, so if you are asking whether to use 1.2.0 or 1.3.0, you are probably using wrong version

**Comment by pauliusguzas** [comment]
@hemko2020 suggest creating new ticket if you have any question on remote focus, I am not able to answer your question atm

**Comment by GabrieleKaceviciute** [comment]
Closing as answer has been provided, feel free to reopen if needed
