### ISSUE TITLE
How can we add target to native iOS project ?

### ISSUE THREAD

**Issue by ParvinderjitSF** [flexn-io/renative#1481]
How can we add Native Target to iOS project. E.g. what if one would like to integrate watchOS app to ReNative app ?

**Comment by ParvinderjitSF** [comment]
Any update on this

**Comment by ParvinderjitSF** [comment]
Any update on this ?

**Comment by ParvinderjitSF** [comment]
Any update on this ?

**Comment by ParvinderjitSF** [comment]
Any Update on This?

**Comment by ElenaDiachenko** [comment]
Closed as duplicate. 

 https://github.com/flexn-io/renative/issues/1552
