### ISSUE TITLE
Migration to latest tooling for Android And iOS?

### ISSUE THREAD

**Issue by ParvinderjitSF** [flexn-io/renative#1482]
By any chance are we planning to move this framework to support latest version of XCode (XCode 15) and Android Studio ?

As apple won't accept the build not compiled with XCode 15 [Ref](https://developer.apple.com/ios/submit/#:~:text=Build%20with%20Xcode%2015&text=Please%20note%20that%20as%20of,and%20the%20iOS%2017%20SDK.)

**Comment by pauliusguzas** [comment]
@ParvinderjitSF hello, 1.0.0-rc.12 supports xcode 15 and other latest tools
