### ISSUE TITLE
How can we remove dependency of ReNative?

### ISSUE THREAD

**Issue by chiragtagadiya4** [flexn-io/renative#1484]
How can we remove the dependency of ReNative from the app?
e.g. Remove ReNative dependency for the Mobile Platforms (iOS and Android) and run it using pure ReactNative.

**Comment by ElenaDiachenko** [comment]
@chiragtagadiya4 Hello, sorry for the late reply. Your question is not entirely clear. Could you please explain in more detail?

**Comment by Marius456** [comment]
There isn't a single uniform answer to this process, as it can vary depending on your specific project. However, here are the main points to guide you through migrating a ReNative project to React Native.
Steps:
1. Main Code Transfer:
- Ensure that the primary codebase resides in the src folder.
- Transfer all relevant files from this directory to your new React Native project.

2. Managing Dependencies:

- For a comprehensive list of plugins used in ReNative, refer to the [ReNative Plugins Overview](https://renative.org/docs/plugins/overview).
- Identify the plugins you need to remove or replace.
- Note that some functions may not have a direct dependency alternative and will require you to create custom functions.

3. Update config files.

By following these steps, you can streamline the migration process while addressing key areas such as code structure and dependency management.
