### ISSUE TITLE
[Tizen] Focus doesn't work  on real device

### ISSUE THREAD

**Issue by hemko2020** [flexn-io/renative#1497]
@pauliusguzas Hello i trying to use remote of my samsung tv but focus doesn't work do you have some solution for resolve this issue? but he work fine on WebOs simulator.

**Comment by GabrieleKaceviciute** [comment]
@hemko2020 Thanks for reporting this issue, could you provide rnv and node versions, os type?

**Comment by GabrieleKaceviciute** [comment]
Closing as duplicate of https://github.com/flexn-io/renative/issues/127
