### ISSUE TITLE
[regression] [androidtv, firetv] only splash screen is displayed on app-harness

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1511]
**Describe the bug**
App is installed on simulator/device but only splash screen is displayed on app harness

**To Reproduce**
1. Go to app-harness package
2. Do `npx rnv run -p androitv` -> observe

**Screenshots or copy&paste**
![androidtv](https://github.com/flexn-io/renative/assets/106537292/20c4ff16-e2d9-408e-a033-d05bb5ed9b1c)

**Desktop (please complete the following information):**
-   OS: macOS Ventura 13.6.4 (M2)
-   Node Version 18.19.0
-   RNV Version 1.0.0-rc.16

**Comment by pauliusguzas** [comment]
works on rc.19
