### ISSUE TITLE
Native player for WebOs and Tizen

### ISSUE THREAD

**Issue by kiriltsts** [flexn-io/renative#1516]
Hello I'm new to ReNative.
I'm planning to create IPTV video player app for WebOs and Tizen TV's.
I have tested the HTML5 video player and some js based playes, but they don't play many types of video or audio codex.

Is there any plugin/framewor that use the native player of the TV?
Or any web based player?

Thanks :)

**Comment by ElenaDiachenko** [comment]
Close as duplicate

https://github.com/flexn-io/renative/issues/661
