### ISSUE TITLE
Some configs for some plugins get override by the RNV. How not to opt that behaviour

### ISSUE THREAD

**Issue by ParvinderjitSF** [flexn-io/renative#1538]
Renative version 0.37.4

Why some plugins default configuration for cocoapods get override and using the podspecs from the @flexn>plugins>plugintemplate>@react-native-firebase>app>override>RNFBApp.podspecs ?

**Comment by ElenaDiachenko** [comment]
@ParvinderjitSF  Hello. To disable plugin overrides, you can use the  `disablePluginTemplateOverrides` property.

```
 "@react-native-firebase/app": {
            "disablePluginTemplateOverrides": true,
            "version": "18.6.1",
            "ios": {
                "podNames": [
                    "pod 'Firebase', :build_type => :static_framework",
                    "pod 'FirebaseCoreInternal', :build_type => :static_framework",
                    "pod 'FirebaseCore', :build_type => :static_framework",
                    "pod 'GoogleUtilities', :build_type => :static_framework",
                    "pod 'FirebaseStorage', :build_type => :static_framework",
                    "pod 'FirebaseAppCheckInterop', :build_type => :static_framework",
                    "pod 'FirebaseAuthInterop', :build_type => :static_framework"
                ],
                "templateXcode": {
                    "Podfile": {
                        "header": ["$RNFirebaseAsStaticFramework = true"]
                    }
                }
            }
        },
```

**Comment by ParvinderjitSF** [comment]
@ElenaDiachenko Is there any way to disable it in ReNative version 0.34? Our project is using this version of the ReNative. Unfortunately we are not in the state to upgrade it to the latest stable one.

**Comment by ElenaDiachenko** [comment]
@ParvinderjitSF In all old versions you can try removing "source:rnv" and adding your own config for the plugin.

**Comment by ElenaDiachenko** [comment]
The answer has been provided. Closing this issue now. Please reopen if you have further questions
