### ISSUE TITLE
No Project Found in Folder when creating env new

### ISSUE THREAD

**Issue by paulNIP** [flexn-io/renative#1550]
No project found when creating new project new

**Comment by GabrieleKaceviciute** [comment]
@paulNIP Thanks for reporting this issue, could you provide log of `rnv new`, also rnv and node versions, os type?

**Comment by paulNIP** [comment]
? What template to use? @flexn/create-template-starter - Advanced multiplatform 
template using flexn Create SDK
✔ Executing: npm view @flexn/create-template-starter versions
✔ Executing: npm dist-tag ls @flexn/create-template-starter
? What @flexn/create-template-starter version to use? 1.2.1 (HEAD: latest)
✖ FAILED: yarn add @flexn/create-template-starter@1.2.1
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 5/14/2024, 11:34:13 AM                                        │
│  $ rnv new                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.4                                                    │
│  Engine: engine-core                                                         │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | x64 | node v20.11.1                                      │
│  Executed Time: 0h:0m:37s:981ms                                              │
│                                                                              │
│ [ error ] [new] COMMAND: 

yarn add @flexn/create-template-starter@1.2.1 

FAILED with ERROR: 

Usage Error: No project found in /Users/paul85alex/Desktop/RhapsodyTV
$ yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...

Command failed with exit code 1: yarn add @flexn/create-template-starter@1.2.1
Usage Error: No project found in /Users/paul85alex/Desktop/RhapsodyTV

$ yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...

Error: Command failed with exit code 1: yarn add @flexn/create-template-starter@1.2.1
Usage Error: No project found in /Users/paul85alex/Desktop/RhapsodyTV

$ yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
    at makeError (/usr/local/lib/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/local/lib/node_modules/rnv/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

**Comment by Parvinderjit** [comment]
Such a unstable framework. We regret used this on production app

**Comment by ElenaDiachenko** [comment]
Can’t reproduce with  latest rnv (1.1.0)
