### ISSUE TITLE
How to integrate Notification Extension in iOS 

### ISSUE THREAD

**Issue by ParvinderjitSF** [flexn-io/renative#1552]
How one can integrate Notification Extension in ReNative ?
We are currently using 0.34.x version. Please suggest us ASAP

**Comment by ElenaDiachenko** [comment]
@ParvinderjitSF   thanks for the question! You can try using platform build overrides. Make the necessary changes in xcode and then add the files you need to change to` your_project/appConfigs/base/builds/ios`. 

[renative docs](https://renative.org/docs/guides/config_folders#special-folders)

**Comment by ParvinderjitSF** [comment]
@ElenaDiachenko In that case can we automate the some parameters like bundle id, developer team and provisioning profile to the Target Extension from the renative.json file ? It will be helpful for us if you can share an example. We have to integrate two extension in the project. One is Watch Extension and other will be for Notification extension

**Comment by ParvinderjitSF** [comment]
@ElenaDiachenko I have added the project file to the appconfigs/base. Now getting hard coded path error on different machine. Actually ReNative injecting absolute path to the project file which creating conflict on the different machine. Can you please suggest ?

**Comment by ParvinderjitSF** [comment]
FYI I have made some changes to the XCodeParser in the SDK-apple in RNV. Now is supports multiple target. One just need to modify the renative.json file format a bit. 
"xcodeproj": {
        "sourceFiles": {
          "RNVApp" : {
            "useTargetNameForGroup" : true,
            "sourceFiles": [
              "RNVApp/RCTPermissionModule.h",
              "RNVApp/RCTPermissionModule.m",
              "RNVApp/RCTWatchPartyHandler.h",
              "RNVApp/RCTWatchPartyHandler.m"
            ]
          },
          "WatchApp" : {
            "useTargetNameForGroup" : true,
            "sourceFiles" :[
              "WatchApp/Bundle+Helper.swift",
              "WatchApp/watchappApp.swift",
              "WatchApp/ZoneCalculator.swift",
              "WatchApp/ZoneView.swift"
            ],
            "resourceFiles" : [
              "WatchApp/WatchFontBold.otf",
              "WatchApp/WatchFontMedium.otf",
              "WatchApp/WatchFontRegular.otf"
            ]
          }
        }
      }
I also need to add the base template into the appconfigs/base/build/ios with the modified xcodeproject file. I copied it from the template folder from the rnv node modules. Hope this could help you guys to have multiple template like watch, notification extension etc or you guys can have option to dynamically adding of these target with some custom scripts. 

Hope this helps you guys to improve the RNV project. Thanks 

[project.xcworkspace.zip](https://github.com/user-attachments/files/16025091/project.xcworkspace.zip)
[xcodeParser.js.zip](https://github.com/user-attachments/files/16025054/xcodeParser.js.zip)

**Comment by ElenaDiachenko** [comment]
@ParvinderjitSF Thank you for your answer. Closing this issue now.

**Comment by ParvinderjitSF** [comment]
Are you guys planning to integrate the solution in the ReNative project ?
