### ISSUE TITLE
Can we use useMemo 

### ISSUE THREAD

**Issue by saimirg** [flexn-io/renative#1554]
Hi, is it possible to use useMemo with scroll view ?

We are experiencing flashlist not being shown at all on certain Tizen TVs, and the only option is Scrollview. But performance with scrollview is very bad, and we tried to use useMemo to improve. However focus is not working at all when combining useMemo with scrollview.

**Comment by pauliusguzas** [comment]
@saimirg hello, are you using plain renative or flexn/create too? what versions of both?

**Comment by saimirg** [comment]
@pauliusguzas find details below:

 Project Version ($package.version): 0.18                  │
│ Workspace ($.workspaceID): flexn                      │
│ Platform (-p): tizen                            │
│ Engine ($.platforms.tizen.engine): engine-rn-web              │
│ Template: @flexn/create-template-starter@1.2.1               │
│ App Config (-c): app                            │
│ Build Scheme (-s): debug                          │
│ Target (-t): T-samsung-5.5-x86                       │
│ Supported Platforms: tizen                         │
│ Env Info: darwin | x64 | node v20.11.1                   │
│ Executed Time: 0h:0m:0s:564ms

**Comment by saimirg** [comment]
@pauliusguzas any update on how to use useMemo or how to show flashlist on Samsung 4 devices ?

**Comment by ElenaDiachenko** [comment]
@saimirg Hello. Could you please specify the flashlist used in your app and provide a minimally reproducible example project to help us clarify the issue?

**Comment by Marius456** [comment]
Closing this ticket because of inactivity. Looks like it is a problem with React Native flashlist on Samsung devices and not with Renative. Feel free to open this ticket again if you have more information about this issue.
