### ISSUE TITLE
https://renative.org not working 

### ISSUE THREAD

**Issue by Parvinderjit** [flexn-io/renative#1573]
**Describe the bug**
https://renative.org not working when opening in browser

**To Reproduce**
- open https://renative.org

**Expected behavior**
Should open the webpage 

**Screenshots or copy&paste**
<img width="1675" alt="Screenshot 2024-05-23 at 8 06 28 PM" src="https://github.com/flexn-io/renative/assets/12973999/e77b4441-73bf-431b-8c1e-2ca32eb1ab92">

**Comment by pauliusguzas** [comment]
Solved
