### ISSUE TITLE
Bug running npx rnv commands

### ISSUE THREAD

**Issue by TDDEL** [flexn-io/renative#1591]
**Describe the bug**
Fails to run **npx rnv start**, or **npx rnv** (any command)

**To Reproduce**
1. Install rnv globally via npm
2. Create new project using **rnv new**
3. Navigate into project and run **npx rnv start** (or any other command with npx rnv)

**Expected behavior**
Should build the project and create all the needed files/directories

![image](https://github.com/flexn-io/renative/assets/25251294/96623101-1393-4ae2-a6f2-5da0a679fafa)

**Desktop (please complete the following information):**

OS: macOS Sonoma 14.4 
Node Version v18.20.3
NPM Version 10.2.4
RNV Version 1.0.0-rc.12
@rnv/template-starter 1.0.0-rc.12

**Additional context**
Was running same steps on older mac.  Received new mac mini today and followed same steps resulting in this error.

**Comment by pauliusguzas** [comment]
@TDDEL thanks for reporting this, please try rc.19, that version should work.

Though there are 2 bugs https://github.com/flexn-io/renative/issues/1564 https://github.com/flexn-io/renative/issues/1508. You can overcome them by choosing all platforms when creating new project and when running something for the first time you will get error, but second time should work

**Comment by pauliusguzas** [comment]
@TDDEL do you have yarn installed globally? this maybe can be causes by not having yarn

**Comment by TDDEL** [comment]
@pauliusguzas Thanks! I was missing yarn globally.  

Everything is working now with version 19 like you suggested

**Comment by TDDEL** [comment]
Solved

**Comment by TDDEL** [comment]
Solved with version 19

**Comment by pauliusguzas** [comment]
@TDDEL glad to help, in next rc both bugs mentioned above should be fixed, as well as you should be able to run project without yarn, only with npm

**Comment by iAMkVIN-S** [comment]
@pauliusguzas Is it still [expected](https://renative.org/docs/guides/apple-silicon#androidtv-android-wear) that running the application on an AndroidTV emulator is not working on Apple Silicon devices (M2 Mac Mini)?

Any recommendations on testing the AndroidTV implementation other than building to a real TV each time?

This thread has been super helpful for us too!

**Comment by pauliusguzas** [comment]
Atm AndroidTV is supported on m1/m2 mac processor without any workarounds

**Comment by TDDEL** [comment]
@pauliusguzas I managed to get tvOS to run but I'm getting an error when trying to run androidTV

![image](https://github.com/flexn-io/renative/assets/25251294/57fcb59b-8b62-4eb1-bae5-f72d24978a2e)

**Comment by pauliusguzas** [comment]
@TDDEL hmm, don't remember this one, maybe try to clean data on simulator, try simulator with different version, I use 29 personally

**Comment by TDDEL** [comment]
@pauliusguzas I found out the issue.  

Because I was setting all of this up on a fresh mac I didn't have a java sdk installed.  I hadn't noticed at first but just slightly above the first error line in the screenshot I posted there was a line mentioning something along the lines of being unable to locate a java sdk.

**Comment by pauliusguzas** [comment]
Closing this ticket as seems like issue was resolved, reopen if needed
