### ISSUE TITLE
[kaios] white blank screen when running on new project

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#1597]
**Describe the bug**
white blank screen when running on new project

**To Reproduce**
1. checkout release/1.0
2. create new project using local template
3. do rnv link
4. do npx rnv run -p web -> in order to prevent other bug
5. do npx rnv run -p kaios
6. follow the rest of instrucation how to launch app here https://github.com/flexn-io/renative/pull/1491#issuecomment-2042118645

**Expected behavior**
App launches

**Screenshots or copy&paste**
![image](https://github.com/flexn-io/renative/assets/65670660/02893659-5657-4bce-9867-dcc2315e9637)

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04.5
- Node Version 18.20.2
- RNV Version 1.0.0-rc.19

**Comment by ElenaDiachenko** [comment]
This issue should be fixed in https://github.com/flexn-io/renative/pull/1590
