### ISSUE TITLE
[kaios] Project doesn't open

### ISSUE THREAD

**Issue by Marius456** [flexn-io/renative#1604]
**Describe the bug**
When you create new project and try to run it, simulator shows white screen.

**To Reproduce**

1. Run command 'rnv new' and select 'kaios' platform
2. Run command 'npx rnv run'
3. See error

**Expected behavior**
Simulator shows template starter page.

**Desktop (please complete the following information):**

-   OS: ubuntu
-   Node Version  v18.19.0
-   RNV Version 1.0.0-rc.19

**Comment by pauliusguzas** [comment]
https://github.com/flexn-io/renative/issues/1597#issuecomment-2149530412 I think this is the same bug and is fixed @Marius456

**Comment by Marius456** [comment]
Closed because it is a duplicate of:
- https://github.com/flexn-io/renative/issues/1597
