### ISSUE TITLE
tizenmobile does not launch correctly if tizen (TV) simulator is launched already

### ISSUE THREAD

**Issue by pavjacko** [flexn-io/renative#164]

**Comment by mihaiblaga89** [comment]
i've encountered the same issue, it takes about 10-15s to launch it for some reason. Even if I manually executed the ares command. Please check again and wait a bit.

**Comment by mihaiblaga89** [comment]
Unstale. I want to check this

**Comment by pauliusguzas** [comment]
Did not notice issues launching tizenmobile simulator while tizen was running, only weird thing I see is that both tizen and tizenmobile use same port, so that might cause issues. In my case tizenmobile app failed on some error, so not sure how same ports are affecting running tizen apps

**Comment by pauliusguzas** [comment]
Not reproduced on 1.0.0. Feel free to reopen
