### ISSUE TITLE
[tizen] Remote control issues on template-starter app (certain device only)

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/renative#1735]
**Describe the bug**
There is no initial focus, but when "Try me!" button is focused and clicked - nothing happens

**To Reproduce**

1. Go to template-starter package
2. Do `npx rnv run -p tizen -t <IP>` -> app launches on device and there is no initial focus
3. Click "OK" on remote control -> "Try me!" button is focused
4. Click "OK" on remote control -> nothing happens

**Expected behavior**
"Try me!" button is initially focused and if it's clicked - dark theme applies on screen

**Desktop (please complete the following information):**

- OS: Ventura 13.6.4 M2
- Node Version 18.19.0
- RNV Version 1.3.0-rc.2
- Device: TV Samsung UE32M5522, OS version 1400 (Test lab label TV11)

Note:
It works on Samsung Tizen UE43NU7192U; OS version 1341 (Test lab label TV5)

**Comment by Marius456** [comment]
It works on device: Samsung Tizen UE32T4302AKXXH; tv-5.5; OS version 2505

**Comment by Marius456** [comment]
After debugging found out that `keydown` event isn't being called when you press button.
Tested by adding:  `window.addEventListener('keydown', () => alert('keydown'));`

`Keyup` event works normally.

`TouchableOpacity` from `react-native` using `onLongPress` only works first time.
