### ISSUE TITLE
Get DeviceId of Samsung (Tizen) TV/Emulator

### ISSUE THREAD

**Issue by MananS77** [flexn-io/renative#225]
This is just a `question` and should be tagged as one.

Say I were to use the built-in template starters, [hello-world](https://www.npmjs.com/package/renative-template-hello-world) or the [blank app](https://www.npmjs.com/package/renative-template-blank). Is there a way to get the `deviceID` of the TV (or the emulator) on which the app is deployed/running using the `Tizen` flavor?

For instance, the `Api` exposes the `platform` in use (as depicted in the `screenHome.js` file). Is there a way to get the `deviceID` flow there as well?

Platform example/snippet:

```
import { Api } from 'renative';

class ScreenHome extends React.Component {
    constructor() {
        super();
    }

    render() {
        return (
              <Text style={styles.textH3}>
                     {`platform: ${Api.platform}`}
              </Text>
              {/*<Text style={styles.textH3}>
                     {`platform: <deviceId>}`} --> How can I show deviceId here? Or device-specific info?
              </Text>*/}

        )
    }
}
export default ScreenHome;
```

**Comment by lukutism** [comment]
https://developer.samsung.com/tv/develop/api-references/tizen-web-device-api-references/systeminfo-api 

Tizen variable should be global in app.

**Comment by MananS77** [comment]
Thank you @lukutism . How would that be used in the `renative` framework, like for instance the `ScreenHome` component?

**Comment by lukutism** [comment]
Try
` componentDidMount(){
console.log(tizen.systeminfo) 
}`

**Comment by KuluGary** [comment]
Hello. I also wanted to be able to access the systeminfo API, but whenever I do something like of ` alert(tizen.systeminfo)` it does nothing, and whenever I try to use:
```
return new Promise((resolve, reject) => {
    resolve(tizen.systeminfo.getAvailableMemory())
})
``` 

It throws an error `DetailReferenceError: tizen is not defined` when running on the simulator. Any workarounds? How can I access this information?

**Comment by GabrieleKaceviciute** [comment]
Closing as answer has been provided, feel free to reopen if needed
