### ISSUE TITLE
Add type checking for config props

### ISSUE THREAD

**Issue by mihaiblaga89** [flexn-io/renative#305]
**Is your feature request related to a problem? Please describe.**
Enforce type checking when parsing the configs.

**Describe the solution you'd like**
Either have another argument in `getConfigProp` specifying what type of data to expect, or separate it into several functions, like `getConfigString`, `getConfigBool`. This will throw an error if, for example, you specify something else than true or false in a prop that's being passed through `getConfigBool`.

**Comment by pavjacko** [comment]
getConfigProp is now TS generics based method which utilizes autogenerated TS schema definitions to extract correct type

**Comment by pauliusguzas** [comment]
@pavjacko @mihaiblaga89 is there a way to test this?

**Comment by pavjacko** [comment]
@pauliusguzas no. it a technical chore. marking it as ready
