### ISSUE TITLE
Grainy images on LG webOS

### ISSUE THREAD

**Issue by andiskim** [flexn-io/renative#345]
The pictures look grainier on the LG webOS as compared to just the web browser.  Is there a way to fix this?

I did a comparison by using the browser on the same LG device as using the developer mode.  The image quality on the developer mode is much more grainier.  Would love some input!

**Comment by pavjacko** [comment]
@andiskim are you talking about actual device or simulator. if device could you provide details of the TV ?

**Comment by andiskim** [comment]
@pavjacko Both the emulator and the TV have blurrier pictures than on the browser.  The device I tested on is a 49 inch LG TV

**Comment by andiskim** [comment]
@pavjacko 

For reference on my computer:
Browser: 
<img width="1437" alt="computer browser" src="https://user-images.githubusercontent.com/6220220/68405779-affea700-014e-11ea-8c5a-0c40e0e11536.png">

Emulator:
<img width="1401" alt="emulator" src="https://user-images.githubusercontent.com/6220220/68405792-b55bf180-014e-11ea-9ffa-171c2f4e5a16.png">

You can see the difference in the writing as well.  It is like this when testing on the LG TV as well (using the inhouse browser vs using development mode in the LG TV).  Any help would be greatly appreciated

**Comment by GabrieleKaceviciute** [comment]
@andiskim thanks for reporting, is this still reproduced on latest version?

**Comment by pauliusguzas** [comment]
can't reproduce on 1.0.0
