### ISSUE TITLE
Tizen-TV with Tizen.NET via react-native-tizen-dotnet possible?

### ISSUE THREAD

**Issue by jfrux** [flexn-io/renative#417]

**Comment by pavjacko** [comment]
@jfrux definitely possible. just didn't have time to get to it just yet.
will mark this as feature request and will put it on the roadmap for better visibility

**Comment by aurimasmi** [comment]
This library https://github.com/onerain/react-native-tizen-dotnet is not updated more than 5 years, therefore it will not be feasible to try to support this library.
