### ISSUE TITLE
Best way to add custom implementations for web-based build that aren't available?

### ISSUE THREAD

**Issue by jfrux** [flexn-io/renative#427]
If I have something like react-native-snap-carousel working in native, and there isn't an exact working version of that carousel in web yet... is there a way to override this elegantly in the code structure?  Is this more of a react / react-native question?

Just trying to gauge how much this is a build tool over a framework / code-structure tool?

**Comment by mihaiblaga89** [comment]
Try using that for web as well. No need to condition it. If that package
doesn't use something that it's not supported by react-native-web it should
work just fine.

**Comment by jfrux** [comment]
@mihaiblaga89 Thanks for the quick response!

I'm wondering if maybe I'm just having standard webpack related issues.
The code is working in tvOS / FireTV since those are based on ones with support.

I've handled this before in regular react-dom based apps... should I just proceed in handling them the same way in this format as well? I'm sorry, these seem like silly questions - but just still trying to wrap my head around the magic of react-native.  Please forgive!

```
ERROR in ./node_modules/react-native-snap-carousel/src/parallaximage/ParallaxImage.js 10:21
Module parse failed: Unexpected token (10:21)
You may need an appropriate loader to handle this file type.
| export default class ParallaxImage extends Component {
| 
>     static propTypes = {
|         ...Image.propTypes,
|         carouselRef: PropTypes.object, // passed from <Carousel />
 @ ./node_modules/react-native-snap-carousel/src/index.js 3:0-58 6:0-84
 @ ./src/components/Header/HeaderView.js
 @ ./src/containers/Root/RootScreen.js
 @ ./src/app.js
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:9999 (webpack)/hot/dev-server.js ./index.web.js
```

**Comment by ElenaDiachenko** [comment]
The answer has been provided. Closing this issue now. Please reopen if you have further questions
