### ISSUE TITLE
Any idea How do I implement TVOS focus guide in renative ?

### ISSUE THREAD

**Issue by jasmeet447** [flexn-io/renative#576]
Hi, I'm trying to build an application in Renative for TVOS platform. The focusable elements in the application are wrapped up in a Touchable Opacity. I'm not sure how to implement focus guides. Any help will be appreciated!

**Comment by RicardasN** [comment]
I suggest looking into @react-native-community/react-native-tvos implementation of FocusGuide and trying to add it to your project using Renative's plugin override features. It's not an easy task, but our solution is not public (although it is based on react-native-tvos project implementation)

https://github.com/react-native-community/react-native-tvos/blob/af56b2ce13e2a7af2062c6a848298850d550c875/React/Views/RCTTVFocusGuideView.m
https://github.com/react-native-community/react-native-tvos/blob/af56b2ce13e2a7af2062c6a848298850d550c875/RNTester/js/examples/TVFocusGuide/TVFocusGuideExample.js

**Comment by jasmeet447** [comment]
@RicardasN, just a quick question:
How can I override react-native with react-native-tvos using rnv override in my current project such that it doesn't affect the code for the other platforms?
The same code is working fine on LG WebOS, Tizen ad Android TV.

**Comment by pauliusguzas** [comment]
Closing as answer has been provided
