### ISSUE TITLE
Can I use react-native-tvos instead of/along with react-native in my renative project?

### ISSUE THREAD

**Issue by jasmeet447** [flexn-io/renative#583]
Hi, I've been developing a project in renative for tvos and I want to use some features that are present in react-native-tvos but not in react-native. Any suggestion might be helpful if I want to use react-native-tvos. Currently, I tried to import react-native-tvos instead of react-native, but it didn't work.

**Comment by aurimasmi** [comment]
What specifically you want to use from react-native-tvos? You can use rnv overrides system in order to bring features like: focus guide, back handler...

**Comment by jasmeet447** [comment]
Yes, I wanted to use the focus guide. But I don't know about rnv overrides system, or how to use them in a renative project. Neither I've heard them before,as I've started working on renative recently. Can you suggest some docs, links, or anything that might help?

**Comment by jasmeet447** [comment]
@aurimasmi, just a quick question: 
How can I override react-native with react-native-tvos using rnv override in my current project such that it doesn't affect the code for the other platforms?
The same code is working fine on LG WebOS, Tizen ad Android TV.

**Comment by aurimasmi** [comment]
That's basically how your structure should look like(ignore firebase):
<img width="320" alt="Screenshot 2020-10-05 at 22 16 21" src="https://user-images.githubusercontent.com/16107073/95121985-82ecb700-0758-11eb-8696-930658c73bbd.png">

So you should add FocusGuide files which you can [find here](https://github.com/react-native-community/react-native-tvos/tree/tvos-v0.63.1/React/Views) to your `appConfigs/base/plugins/react-native/` and what rnv does it will pick it up those files and copy them to the same same folder in node_modules during the build.

After than you will be able to [import FocusGuide in your JS code](https://github.com/react-native-community/react-native-tvos/blob/af56b2ce13e2a7af2062c6a848298850d550c875/Libraries/Components/AppleTV/TVFocusGuideView.js)

**Comment by jasmeet447** [comment]
Hello @aurimasmi, I tried to add the following files under the hierarchy appConfigs/base/plugins/react-native/overrides/React/Views :
1. RCTTVFocusGuideView.h
2. RCTTVFocusGuideView.m
3. RCTTVFocusGuideViewManager.h
4. RCTTVFocusGuideViewManager.m
5. RCTTVView.h
6. RCTTVView.

After doing so, I added the file TVFocusGuideView.js under the hierarchy:
appConfigs/base/plugins/react-native/overrides/Libraries/Components/AppleTV.

As you told me earlier, rnv did pick those files and put them in the node modules in their respective folders. Unfortunately, I get an error while running the app with the description below:
"Invariant Violation: Element type is invalid: expected a string(for built-in components) or a class/function (for composite components) but got: undefined. you likely forgot to export the component from the file it's defined in, or you might have mixed up default and named imports."

If I remove/comment out the calls of <TVFocusGuideView> in the render, my application runs fine. It only fails when I call <TVFocusGuide> inside the render.
I've also attached a reference for the error. Any help will be appreciated.

<img width="1904" alt="Screenshot 2020-10-06 at 3 30 28 PM" src="https://user-images.githubusercontent.com/44059494/95189836-0c00fe00-07ec-11eb-8aea-1a9443bebfa1.png">

**Comment by aurimasmi** [comment]
I'd suggest you to put `TVFocusGuideView.js` into your actual src instead of react-native overrides in that case you have full control, because I'm pretty sure this error occurrs because it can't find your `TVFocusGuideView.js` which sits in node_modules currently.

**Comment by jasmeet447** [comment]
@aurimasmi, I followed your suggestion and was able to build a focus guide view in a demo renative project with a single screen. When I tried to implement the same thing on my ongoing project, it shows me an error while using focus guide.(I implemented it the same as I did on my demo project).
Here is the reference, Can you tell me what's wrong in it?

<img width="1725" alt="Screenshot 2020-10-07 at 5 18 28 PM" src="https://user-images.githubusercontent.com/44059494/95327428-a717d780-08c1-11eb-924d-87d6fa5a7336.png">

**Comment by aurimasmi** [comment]
Well the error is pretty explanatory as you have two different view files under the same name. In order to help you here I'd need to see your source code

**Comment by jasmeet447** [comment]
I can show you my code over a call(google meet, skype, zoom, etc). Please give me a suitable time for the call and we'll connect with you over there.

**Comment by jasmeet447** [comment]
@aurimasmi, We're stuck because of this issue for a long time and cannot submit our app on the AppStore.So please let me know a suitable timing for a call where we can discuss the issue.

**Comment by aurimasmi** [comment]
@jasmeet447 unfortunately I can't make a call any time soon. If your project is not very sensitive in a terms who can see the code just invite me there and I'll take a look in one of my night coding sessions. Other option that we will inject Focus Guide to renative so it will come out of the box, hopefully I can take a lot into this next week

**Comment by jasmeet447** [comment]
Hi @aurimasmi, I was able to debug the root cause of the issue that the focus guide couldn't be implemented in my project. It seems that there is some error with the constraints relative to other elements in the render method. I came to know that if I remove some components, I could see the focus guide working well. If I included that component again, I see an error( refer to the screen-shot.) I see this kind of error on other screens also in my project.
Strange thing is that I see no error if I use any other View with the exact same styles in place of the focus guide, whether the component causing the error with the focus guide in the view is included in the render or not. 
Any suggestions will be helpful.

<img width="1884" alt="Screenshot 2020-10-12 at 11 52 23 AM" src="https://user-images.githubusercontent.com/44059494/95712502-77cae700-0c82-11eb-8e3f-34050ac4251f.png">

**Comment by RicardasN** [comment]
> Hi @aurimasmi, I was able to debug the root cause of the issue that the focus guide couldn't be implemented in my project. It seems that there is some error with the constraints relative to other elements in the render method. I came to know that if I remove some components, I could see the focus guide working well. If I included that component again, I see an error( refer to the screen-shot.) I see this kind of error on other screens also in my project.
> Strange thing is that I see no error if I use any other View with the exact same styles in place of the focus guide, whether the component causing the error with the focus guide in the view is included in the render or not.
> Any suggestions will be helpful.
> 
> <img alt="Screenshot 2020-10-12 at 11 52 23 AM" width="1884" src="https://user-images.githubusercontent.com/44059494/95712502-77cae700-0c82-11eb-8e3f-34050ac4251f.png">

What helped me when I encountered this issue is just resetting the cache.
`npx rnv start -p tvos -r`
After that I never saw this issue pop up again, hope it helps you as well :)

**Comment by TheDuc** [comment]
if you want to use react-native-tvos instead of react-native, you can specify that in renative.json.

for example:
_renative.json_
```json
    "plugins": {
       (...)
        "react-native": {
            "version": "npm:react-native-tvos@0.61.5-1",
        },
       (...)
    }
```

**Comment by RosaryDarling** [comment]
Judging from discussion above, closing this issue as solved - if it is still persistent, please feel free to reopen this ticket
