### ISSUE TITLE
npx rnv run -p tvos -t "Apple TV 4K" start iPhone 8 emulator

### ISSUE THREAD

**Issue by RobertArissen** [flexn-io/renative#616]
Hello,

I run the command `npx rnv run -p tvos -t "Apple TV 4K"` the result is that the terminal open a iPhone 8 simulator instead of an Apple tv emulator

Does anyone know what could be causing this?

**Comment by pavjacko** [comment]
@RobertArissen never seen this before 🤔  . 
few thing to try:
what do you get if you run:

A)

`npx rnv run -p tvos` (no target param)

B)

`npx rnv run -p tvos -t` (empty target should give you list of options)

C) 

What is defined in your `~/.rnv/renative.json` file under `tvos`. ?

additionally it always helps to post SUMMARY box from the console

**Comment by RosaryDarling** [comment]
Closing this ticket as it seems like the answer has been provided. If the issue persists - please feel free to reopen this ticket
