### ISSUE TITLE
Renative Tizen View focus with Remote clicks 

### ISSUE THREAD

**Issue by YogeshRewan1** [flexn-io/renative#626]
In My Tizen  App, There are dynamic view Generated  and I have used view, touchablity use for design Purpose 
MY issue is I have to Navigate/Focus in layout with remote control i.e Left, Right, Up and Down as shown in Template (Used Button in Template)

**Comment by pavjacko** [comment]
@YogeshRewan1 hello world example uses `react-spatial-navigation` (you can of course use different library if desired)
to customize the focus logic and key mapping check https://github.com/NoriginMedia/react-spatial-navigation#setting-initial-focus-on-child-component-tracking-children

**Comment by RosaryDarling** [comment]
Closing this ticket as the answer has been provided - feel free to reopen it if the issue persists
