### ISSUE TITLE
[tvOS] error The `device` and `udid` options are mutually exclusive.

### ISSUE THREAD

**Issue by TheDuc** [flexn-io/renative#638]
**Describe the bug**
When running on device `rnv run -p tvos -d -t "DeviceName" --skipTargetCheck` the app is not installed on TV.
The command `node /Path/to/Project/node_modules/react-native/local-cli/cli.js run-ios --project-path platformBuilds/projectname_tvos --scheme RNVAppTVOS --configuration Debug --simulator DeviceName` fails with ```error The `device` and `udid` options are mutually exclusive.```

**Desktop (please complete the following information):**

-   xcode 12.3
-   RNV Version 0.32.0-alpha.25

**Additional context**
https://github.com/pavjacko/renative/blob/172d815d0f025a0584c218ace3195fb5ce7ceeb8/packages/rnv-engine-rn/src/sdks/sdk-xcode/index.js#L211
https://github.com/pavjacko/renative/blob/172d815d0f025a0584c218ace3195fb5ce7ceeb8/packages/rnv-engine-rn/src/sdks/sdk-xcode/index.js#L195
I believe `--device` should be removed from these lines, because it is mutually exclusive with `--udid`

**Comment by TheDuc** [comment]
any progress on this?

**Comment by GabrieleKaceviciute** [comment]
@TheDuc Thanks for reporting, is this still reproduced on latest version?

**Comment by TheDuc** [comment]
I haven't used ReNative in a while, so not 100% sure. But the exact changes I suggested in the opening post have been implemented a while back in [this commit](https://github.com/flexn-io/renative/commit/f6abb37f20b6c4cbf9bf7661a188e94bf79b1c43), so I'm guessing this can be considered fixed 👍

**Comment by GabrieleKaceviciute** [comment]
Closing as issue was resolved
