### ISSUE TITLE
Tizen tabBar '../components/menu'

### ISSUE THREAD

**Issue by elStranger** [flexn-io/renative#657]
Hi, 
I've just discovered your library. Great Job thanks for that.

Is it possible to hide the menu on the Tizen App. Or auto-hide it? Because when I delete/comment it 
```
    <TabStack.Navigator
        // tabBar={ props => <Menu { ...props } /> }
        removeClippedSubviews
        swipeEnabled={ false }
        timingConfig={ { duration: 0.001 } }
    >
        <TabStack.Screen name="home" component={ ScreenHome } />
        <TabStack.Screen name="my-page" component={ ScreenMyPage } />
    </TabStack.Navigator>
```

it's still here

**Comment by ali-sao** [comment]
The Tab bar is inside `index.tv.native.js` file , which has nothing to do with Tizen. any edits there will only affect Android and tvOS. Edit `index.web.js ` instead

**Comment by GabrieleKaceviciute** [comment]
Closing as has been answered, feel free to reopen if needed
