### ISSUE TITLE
Video Component for WebOs, Windows, Tizen Tv.

### ISSUE THREAD

**Issue by AbelValdez** [flexn-io/renative#661]
Im looking for a Video plugin for all other platforms like  WebOs, Windows, Tizen Tv. because react-native-video its only for 
os,tvos,android,androidtv.

I would like to know if already exist a plug in with this features.

**Comment by egemenuzunali** [comment]
I would also like to know if it is possible to play videos on tizen using renative

**Comment by ali-sao** [comment]
You can pick any player you wish that suits your needs and create a platform specific file for this purpose, like `player.tv.web.js`

**Comment by egemenuzunali** [comment]
Hi @ali-sao do you have an example for tizen ?

**Comment by ali-sao** [comment]
@egemenuzunali , depends on your use case. For Tizen 2.3 and 2.4, your most appropriate player would be AVplay. While for 3.0+ you can choose one of many players online. Beside on which type of media are you consuming.

**Comment by SandeepKharbanda** [comment]
You can use React-player https://www.npmjs.com/package/react-player. I have used the same player for Tizen, WebOS, and Windows.

**Comment by ElenaDiachenko** [comment]
The answer has been provided. Closing this issue now. Please reopen if you have further questions
