### ISSUE TITLE
How to do renative development

### ISSUE THREAD

**Issue by rfestag** [flexn-io/renative#665]
First, thanks for all the great work on this, I'm really enjoying playing with renative!

I have a few patches in a fork I made that I'd like to test. I manually made the changes to my local 0.31.3 install, but I see that the master is at an alpha of 0.32. The documentation implies that if I run `yarn bootstrap` and `yarn watch`, that it should be used instead of my global install. Unfortunately, that doesn't seem to be the case...as far as I can tell, it is still using my 0.31.3.

Am I missing something?

**Comment by EyMaddis** [comment]
you need to also run `yarn link renative` inside your project to tell yarn to use the local renative version instead of the files inside node_modules

**Comment by GabrieleKaceviciute** [comment]
Closing as answer has been provided, feel free to reopen if needed

**Comment by GabrieleKaceviciute** [comment]
@bruno-sartori please follow contribution documentation
https://github.com/flexn-io/renative/blob/main/CONTRIBUTING.md
