### ISSUE TITLE
How can I detect windows machine id in Renative?

### ISSUE THREAD

**Issue by SandeepKharbanda** [flexn-io/renative#668]
Hello,

How can we detect windows machine id in Renative? we have tried it using node-machine-id i.e https://www.npmjs.com/package/node-machine-id package but we're unable to create a release build after integrating the node-machine-id library. We are getting the below error:
Can't resolve 'child_process' in ' \node_modules\node-machine-id\dist'.

Any suggestion would be appreciated.

Thanks in advance!

**Comment by pauliusguzas** [comment]
@SandeepKharbanda Thanks for reporting this issue. What versions did you use of rnv, node? Is this still reproduced on latest rnv version?
