### ISSUE TITLE
[webOS] webpack dev server does not serve webOSTVjs-1.1.1/webOSTV.js

### ISSUE THREAD

**Issue by apostopher** [flexn-io/renative#712]
**Describe the bug**
as per the [webOS SDK](https://webostv.developer.lge.com/api/webostvjs/intro-webostvjs/) the webOSTV.js file does not load in the freshly created project.

**To Reproduce**

1. create a new rnv project
2. run the app on LG TV device -> `rnv run -p webos -d`.
3. debug the app to see 404 errors for `webOSTV.js` and `webOSTV-dev.js`

<img width="536" alt="CleanShot 2021-08-25 at 15 08 37@2x" src="https://user-images.githubusercontent.com/270924/130742981-5035dc60-ae35-48c7-9659-a156e3e93e18.png">

**Expected behavior**
the webOS SDK files load properly

**Desktop (please complete the following information):**

-   OS: macOS Big Sur and running on LG TV
-   Node Version [v12.22.3]
-   RNV Version [0.31.3]

**Comment by ngethe** [comment]
Hi @apostopher how did this go did you solve it ?
looking for complete streaming solution let me know if you have it

**Comment by brunosartori-agile** [comment]
Any updates on this issue?

**Comment by GabrieleKaceviciute** [comment]
@apostopher thanks for reporting this issue, is this still reproduced on latest (0.37.1) version?
