### ISSUE TITLE
WebOS and Tizen apps dont load after export

### ISSUE THREAD

**Issue by HernanPaez** [flexn-io/renative#769]
Hi! I am working on an app for smart tvs (webos and tizen) and everything is working fine when I run the app using the rnv run command but, when I try to export a release build, it isn't loading and it shows only a white screen.

I know that the development build uses webpack and the app only loads an iframe. Knowing this I added a new build configuration for my app using the information I got from other issues 

```
        "webos": {
            "entryFile": "index.webos",
            "buildSchemes": {
                "debug": {
                    "bundleAssets": false,
                    "environment": "development"
                },
                "release": {
                    "bundleAssets": true,
                    "environment": "production"
                }
            }
```

AFAIK This allows me to run the app in both debug and release modes. But this hasn't changed anything, debug build works great and the release build only shows a white screen.

I don't know if this is a problem of how the index.html is generated. I started a simple web server and when I open it using Chrome the index.html route (http://localhost:5000/index.html) doesn't load anything just like the app, it loads fine if I remove the index.html from the url (http://localhost:5000/)

This issue is also present in the HelloWorld template with the exception that it only loads the menu. The content below is always displayed as a black box.

Can you give me any suggestion to solve this? I have my app almost ready for release but this issue is making me crazy

I am using Renative 0.33.0 and I also built my app using the blank template

**Comment by JoaoCEAlmeida** [comment]
Hi, I'm facing the same problem...I fixed using the following on the renative.json to override the default:

    "webos": {
      "entryFile": "index.webos",
      "buildSchemes": {
        "debug": {
          "bundleAssets": false
        },
        "release": {
          "bundleAssets": true,
          "bundleIsDev": false,
          "webpackConfig": {
            "devServerHost": "0.0.0.0",
            "baseUrl": "/media/developer/apps/usr/palm/applications/$YOUR_APP_ID"
          }
        }
      }
    }

But this is not correct, it works using ares to install the ipk...but when the app is install using the lg store that path on the baseUrl is different. Because of this, I'm getting my app not approved by the LG.

\cc @pavjacko

**Comment by pchmelar** [comment]
`rnv export` doesn't work for me, I ended up using `rnv build -p tizen -s release`

**Comment by Alexandrusandy** [comment]
HernanPaez in your index.web.js put this in useEffect         navigate('/', { replace: true }) works for me.

**Comment by makenshikuro** [comment]
Hi everyone.
I have the same problem but I can't fix it.
I can export to web, android and Android TV perfectly but tizen and webOS shows a white screen.
When I export tizen/webOS in hosted web version it's works well.
I tried to do your methods but didn't work.
I think that i'm not doing something we'll.
Can't someone explain more about these fixes for TV exports, please?
Thank you!
I'm using 36.1 version of renative.

**Comment by socialweb-iaraya** [comment]
> This fixed my problem on webos.
> 
> I hope it help us guys.
> 
> Inspired by: https://webostv.developer.lge.com/api/webostvjs/webos/
> 
> ![image](https://user-images.githubusercontent.com/9196047/153906381-b74a1f04-ad57-4f65-bd27-1878b53c61d9.png)
> 
> \cc @pavjacko

Hey @JoaoCEAlmeida , can you elaborate a little bit further on how to implement your solution? Thanks.

**Comment by JoaoCEAlmeida** [comment]
@socialweb-iaraya 

I'm not working anymore on the project, but the solution was to add that "try" "catch" block to the root index.webos.js file.

**Comment by makenshikuro** [comment]
Hi again.
@socialweb-iaraya, @JoaoCEAlmeida. I didn't find the index.webos.js file. All files are tsx extension.
What is de path?
Thanks
![project](https://user-images.githubusercontent.com/6000591/184115532-07b67e25-6ce9-4a99-9c8f-6211b0fad020.png)
s

**Comment by nhjuhoang** [comment]
me too, can you help me to solve it?

**Comment by pauliusguzas** [comment]
related to https://github.com/flexn-io/renative/issues/925

**Comment by GabrieleKaceviciute** [comment]
Since export was disabled on webOS and Tizen, you could try to build app and then install to device. It works for me on rnv 1.0.0-rc.18

**Comment by GabrieleKaceviciute** [comment]
Closing as answer has been provided, feel free to reopen if needed
