### ISSUE TITLE
Plugin Installation Failed

### ISSUE THREAD

**Issue by wwwebgainss0** [flexn-io/renative#776]
Hi,

I am trying to install react player but when I run renative for web. the error "the module is not found" appears.

Steps:
Installation via npm
Adding Plugint to renative.json
rnv run -p web (after running this command, the error appears and the system deletes automatically the plugin folder)

can pls somebody help
THX in Advance

**Comment by mihaiblaga89** [comment]
How exactly did you add it to `renative.json`?

**Comment by GabrieleKaceviciute** [comment]
Closing as answer has been provided, feel free to reopen if needed
