### ISSUE TITLE
Unable to run project on webOs 4.5 due to spread operator

### ISSUE THREAD

**Issue by danielz-nenda** [flexn-io/renative#802]
**Describe the bug**
Trying to run a renative project on a LG WebOS 4.5 device fails due to the use of spread operator in the @react-navigation package.

**To Reproduce**

1. Run command 'rnv run -p webos -d'
2. See error in LG dev console

**Expected behavior**
The minified version of the module should be transpiled to not use spread since it's not supported on older devices.

**Screenshots or copy&paste**
bundle.js:12062 Uncaught SyntaxError: Unexpected token ...

<img width="964" alt="Screenshot 2022-02-09 at 18 39 35" src="https://user-images.githubusercontent.com/74965667/153259239-833f0315-ab2a-42f4-952d-609010c1577a.png">

**Desktop (please complete the following information):**

- OS: Mac OSX 11.6.2 (M1)
- Node Version v14.17.0
- RNV Version 0.35.0 (also tried 0.34.0)

**Additional context
There are no clear instructions in the docs on how to customize the babel/webpack behavior when it comes to polyfill and transpiling of javascript for older devices.

**Comment by samuelbezerrab** [comment]
Same issue here.

**Comment by RobertArissen** [comment]
Same issue here, do you have a solution?

**Comment by danielz-nenda** [comment]
> Same issue here, do you have found a solution?

Unfortunately not. I gave up on Renative and created my own react-project with LG build pipeline.

**Comment by RobertArissen** [comment]
Is it possible to share you'r pipeline solution?

**Comment by GabrieleKaceviciute** [comment]
I can't reproduce it on rnv 1.0.0-rc.18. I've tested on macOS Ventura 13.6.4, Node v18.19.0. On both webOS devices:
````
➜  ~ ares-device-info --device webOS_TV_UN74003LB
modelName : 43UN74003LB
sdkVersion : 5.5.0
firmwareVersion : 04.50.56
boardType : K6LP_DVB_EU
otaId : HE_DTV_W20P_AFADABAA

➜  ~ ares-device-info --device webosTV
modelName : 32LK610BPLB
sdkVersion : 4.4.0
firmwareVersion : 05.50.15
boardType : M3_DVB_EU
otaId : HE_DTV_W18R_AFAAABAA
➜  ~
