### ISSUE TITLE
The project's Babel config is invalid: Cannot read properties of undefined (reading 'uid')

### ISSUE THREAD

**Issue by r0oto0r** [flexn-io/renative#820]
Hey everyone,

**Describe the bug**
I tried to start the blank page default project but I'm getting bable errors during building stage saying that

>> The project's Babel config is invalid: Cannot read properties of undefined (reading 'uid')

This is breaking the build and I can't start the project. Strange enough, If I start the helloworld-template it works just fine - same setup.

**To Reproduce**
Setup new project with blank page template (v.0.34) and try running it with rnv run -p web

**Expected behavior**
A clean build / nextjs startup which actually shows up in the browser

**Screenshots or copy&paste**
![image](https://user-images.githubusercontent.com/8968603/155313685-91a8af6f-cda7-48d1-baed-d0b16597deb3.png)

**Desktop (please complete the following information):**

-   OS: windows 7 10.0.19044
-   Node Version v16.13.1
-   RNV Version 0.34.0

Maybe someone can help?

Thanks and cheers,
Ben

**Update**
Recreated the project with node 14.18.2 and the error goes away. Now I can't seem to run builds for any targets involving webpack like webos throwing this error:
![image](https://user-images.githubusercontent.com/8968603/155506729-92b9e384-4ce3-4b72-9319-ed71af1e7107.png)

**Comment by r0oto0r** [comment]
Recreated the project with node 14.18.2 and it works just fine. So, we can't have node 16?

**Comment by lednewcrk** [comment]
+1

**Comment by mihaiblaga89** [comment]
@r0oto0r @lednewcrk can you please try the latest version? I just tested this and I can't replicate it. Created a new project, picked template-blank and ran it on web, seems to work just fine

**Comment by pauliusguzas** [comment]
@r0oto0r hello, did latest versions fix your issue?

**Comment by r0oto0r** [comment]
Hey, sorry I moved away from this project in the end, so we can close this issue. Thanks for your help!
