### ISSUE TITLE
How do I use Flipper with Renative?

### ISSUE THREAD

**Issue by whenmoon** [flexn-io/renative#853]
How do I use Flipper with Renative? There is no mention of it in the docs and Renative obscures the setup in the official documentation: https://fbflipper.com/docs/getting-started/react-native-android/

I am using Renative version 0.35.4

**Comment by NickAVolpe** [comment]
I think we will need [react-native-tvos engine](https://github.com/react-native-tvos/react-native-tvos#:~:text=Flipper%3A%20Working%20in,newer%20Xcode%20versions.) to add the support. I think the maintainer of that repo has tried pretty hard to get it set up for us there. 

https://github.com/react-native-tvos/react-native-tvos/issues/293

**Comment by mihaiblaga89** [comment]
We'll have to create a plugin for it, since it needs native code injections. It would need something similar to [this](https://github.com/renative-org/renative/blob/canary/packages/rnv/pluginTemplates/renative.plugins.json#L115)

**Comment by whenmoon** [comment]
Thanks for the reply @mihaiblaga89, I think this would be a huge enhancement to Renative.

**Comment by ElenaDiachenko** [comment]
1.0.0-rc.18.
Flipper can be configured in renative. json via `flipperEnabled `property, by  default it is enabled for android based platforms and ios.  For tvos is flipper  disabled because  it has a lot of dependencies that are built for iOS only.

**Comment by GabrieleKaceviciute** [comment]
Closing as answer has been provided, feel free to reopen if needed
