### ISSUE TITLE
set hook  and redux cause performance issues

### ISSUE THREAD

**Issue by maxiannunziata** [flexn-io/renative#854]
Hello everyone,

We are developing an application with Renative and we have the inconvenience that when we want to change a state from a component, the application begins to have performance problems. Is there any alternative/plugin to hooks for handle states?

**Comment by mihaiblaga89** [comment]
What platform are you developing for?

**Comment by mihaiblaga89** [comment]
A renative project is just a react-native one for android-tv, nothing else. Giving the fact that I can't know what's in your project here's some pointers, maybe it will help.

- Have you encountered this performance issue on sim or on device? If device, maybe it's a lower end device? Or if sim then I would try a device
- Development or production? Development will slow down things a bit and if it's a lower end device/dev machine (or you don't have hardware virtualization for the sim) you might feel it.
- Check the code, maybe that state change triggers too many rerenders or some loop

**Comment by maxiannunziata** [comment]
Thank you @mihaiblaga89 

Another question. I saw the new implementation with lightningjs. You have some template or boilerplate of the implementation with Renative?

Thank you!

**Comment by mihaiblaga89** [comment]
@maxiannunziata @SatadruBhattacharjee template that uses lightning https://github.com/flexn-io/flexn#readme
