### ISSUE TITLE
enable Hermes

### ISSUE THREAD

**Issue by matiasmateu** [flexn-io/renative#855]
I'm trying to activate Hermes without any success.

I tried this already:

1 - Make sure that "reactNativeEngine": "hermes" in the renative.json of the template
![Screen Shot 2022-05-12 at 11 48 42](https://user-images.githubusercontent.com/46417651/168043555-53340b03-868e-4cc4-a670-64338ccc7351.png)

2 - Run the app with -r to generate the platformBuild folder again.

3 - After this if I check global.HermesInternal in runtime it always returns false.

-----

Another thing that I tried is to create a new build.gradle and add this piece of code:
![Screen Shot 2022-05-12 at 11 52 10](https://user-images.githubusercontent.com/46417651/168043858-7d182f41-a27f-43af-b939-ac53dacbc684.png)

This doesn't work neither.

----

**Comment by mihaiblaga89** [comment]
the second variant should not work but the first one should. Can you set that, run it with `-r` and then check `platformBuilds/xxx_android` folder if rnv enabled it correctly.

**Comment by matiasmateu** [comment]
![Screen Shot 2022-05-12 at 12 30 52](https://user-images.githubusercontent.com/46417651/168051254-6041f3fc-5214-498a-802e-d3597f00ed54.png)

yes, it updates the build.gradle

But then in runtime I always get global.HermesInternal = false. And also Chrome Debugger doesn't find any Hermes app

**Comment by mihaiblaga89** [comment]
looking at the hermes docs that's all you need to do for android. We'll have to investigate this further

**Comment by matiasmateu** [comment]
Thanks!

**Comment by matiasmateu** [comment]
I'm not sure if this helps. But I get global.HermesInternal = true after this change:

hermesCommand: "{{PATH_HERMES_ENGINE}}/%OS-BIN%/hermes",
vs
hermesCommand: "{{PATH_HERMES_ENGINE}}/%osx-bin%/hermesc",

![Screen Shot 2022-05-12 at 13 27 00 (2)](https://user-images.githubusercontent.com/46417651/168064491-64ed7fde-e874-45d6-9a1c-edc7ff6f1767.png)

**Comment by pauliusguzas** [comment]
Actual hermes engine is working as default but can't override it with other engines on 1.0.0-rc.6 new project

**Comment by ElenaDiachenko** [comment]
@GabrieleKaceviciute  @pauliusguzas  1.0.0-rc.7. Hermes works  in the repo and in new project as well.  How to check: modify renative. json by set other engine.  For example:
` "platforms": {
        "android":{
            "reactNativeEngine": "v8-android"
        }
    },`
