### ISSUE TITLE
error: unknown option `--allowProvisioningUpdates' on iOS

### ISSUE THREAD

**Issue by janMoudry** [flexn-io/renative#864]
**Describe the bug**

When I try to run code on iOS I got this error.
It appeared when I want to upgrade rnv from 0.32.0-alpha.42 to 0.35.3.
I am not able to run this on real Iphone device.

`│ [ success ] [run] Found one device connected! device name: My - iPhone (15.4.1) udid: 00008110-000A28D11EF3801E
│ [ error ] [run] COMMAND: 

node /Users/***/node_modules/react-native/local-cli/cli.js run-ios --project-path platformBuilds/slovaktel_ios --scheme RNVApp --configuration Debug --udid 00008110-000A28D11EF3801E --allowProvisioningUpdates 

FAILED with ERROR: 

error: unknown option `--allowProvisioningUpdates'

Command failed with exit code 1: node /Users/j***/node_modules/react-native/local-cli/cli.js run-ios --project-path platformBuilds/slovaktel_ios --scheme RNVApp --configuration Debug --udid 00008110-000A28D11EF3801E --allowProvisioningUpdates
error: unknown option `--allowProvisioningUpdates'

error: unknown option `--allowProvisioningUpdates'

Error: Command failed with exit code 1: node /Users/***/node_modules/react-native/local-cli/cli.js run-ios --project-path platformBuilds/slovaktel_ios --scheme RNVApp --configuration Debug --udid 00008110-000A28D11EF3801E --allowProvisioningUpdates
error: unknown option `--allowProvisioningUpdates'
    at makeError (/Users/j***/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/***/node_modules/rnv/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
`
**To Reproduce**
upgrade rnv from 0.32.0-alpha.42 to 0.35.3.
upgrade react-native from 0.61.2 to 0.63.4.
run "npx rnv run -p ios -s debug -d -c"

1. Run command 'npx rnv run -p ios -s debug -d -c '
2. See error "error: unknown option `--allowProvisioningUpdates'"

**Expected behavior**
should run 

**Screenshots or copy&paste**
![Screenshot 2022-06-05 at 23 32 50](https://user-images.githubusercontent.com/97884823/172071545-e8537d1e-c47a-4fc6-846b-d2e6e7949408.png)
![Screenshot 2022-06-05 at 23 26 39](https://user-images.githubusercontent.com/97884823/172071548-2837b7dc-a7c9-42dc-ba7d-753f0e71af6f.png)

**Desktop (please complete the following information):**

-   OS: macOs version: 12.3.1 (21E258)
-   Node Version [v14.16.1]
-   RNV Version [0.35.3]
-   Xcode version [13.3] 

**Additional context**

**Comment by GabrieleKaceviciute** [comment]
@janMoudry Thanks for reporting this issue, can you confirm that on the latest version (v0.37.1) you are getting same error as in this ticket https://github.com/flexn-io/renative/issues/1060 ?

**Comment by GabrieleKaceviciute** [comment]
closing this, feel free to reopen if needed
