### ISSUE TITLE
[fireTV, AndroidTV] Template starter focus issues on Home screen

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#869]
**Describe the bug**
Template starter has focus issues on Home screen

**To Reproduce**

- [ ] 1. fireTV, Atv
1. Home screen is open AND focus is on "Try me!" button 
2. Click up
3. Focus is lost -> Focus should be on "Try me!" button

- [ ] 2. fireTV, Atv
1. No focus initially after app is opened

**Desktop (please complete the following information):**
- OS: macOS Monterey 12.6
- Node Version: 16.14.2
- RNV Version: 0.37.0-rc.9
- @rnv/template-starter: 0.37.0-rc.9

**Comment by GabrieleKaceviciute** [comment]
@rnv/template-starter: 0.38.0-canary.1

- [ ] tvOS - button is not focused at all
- [ ] androidTV - No focus initially after app is opened, but when button is focused color doesn't change

**Comment by GabrieleKaceviciute** [comment]
@rnv/template-starter: 1.0.0-rc.18

- webos, tizen -> button is not focused at all

**Comment by GabrieleKaceviciute** [comment]
webos, tizen issue is tracked on https://github.com/flexn-io/renative/issues/1579
