### ISSUE TITLE
Template starter design issues

### ISSUE THREAD

**Issue by pauliusguzas** [flexn-io/renative#872]
**Describe the bug**
**Android (OnePlus6, Android 11)**
- [ ] Safe area should use app color
<img width="401" alt="Screenshot 2023-11-21 at 09 58 58" src="https://github.com/flexn-io/renative/assets/65670660/81bf4cc9-20dc-4435-a426-4c027356cf1d">

**Desktop (please complete the following information):**

- OS: macOS Monterey 12.6
- Node Version: 16.14.2
- RNV Version: 0.37.0-rc.9
- @rnv/template-starter: 0.37.0-rc.9

**Comment by pavjacko** [comment]
@pauliusguzas template-starter has been simplified so this use case is no longer relevant
