### ISSUE TITLE
[IOS] Does Renative Support IOS App Extensions ?

### ISSUE THREAD

**Issue by iMokhles** [flexn-io/renative#877]
i'm developing an application for iOS and i need to add Push Notification support to it
and to do it we need to add a new App Extension Target called ( Notification Service Extension ) using Xcode,
but to persist it i copy the xcodeproj and other files related to it to ( appConfigs/base/build/ios )
so when i run rnv command with -r it won't reset my project,

i'm asking if there are a simple way to do that ?
such as support configuring multiple bundle_id for each target ( main app and app extension )
support configuring multiple provision profiles for each target ( main app and app extension )
and support other configuration such as ( codeSignIdentity, teamID, entitlements etc ) for each target ( main app and app extension )
and add support for multiple Podfile targets

**Comment by iMokhles** [comment]
Any updates on this ?

**Comment by ElenaDiachenko** [comment]
Closed as duplicate.

- https://github.com/flexn-io/renative/issues/1552

**Comment by iMokhles** [comment]
@ElenaDiachenko which one is duplicated, the one created over 2yrs ago or the one is recently added 4 months ago,
beside that, i have explained how to acheive that, but my questions is completely different than #1552
