### ISSUE TITLE
React-native-google-cast not working

### ISSUE THREAD

**Issue by fabio-carvalho88** [flexn-io/renative#906]
Hello! I'm currently setting up react-native-google-cast package in my project, for both Android and iOS. 
I think I have everything I need to complete the Android Installation & Setup steps, however I'm stuck on this:

```
  const client = useRemoteMediaClient();

  if (client) {
    client.loadMedia({
      data
    });
  }
```

![image](https://user-images.githubusercontent.com/45637344/186458484-e9114399-8b0c-4382-be58-98009e2b24ff.png)

I'm using **renative: 0.31.1** and **react-native: 0.61.2** to develop apps for both Android and iOS. 
Dependencies were inserted in `android/app/build.gradle` accordingly to the [Docs](https://react-native-google-cast.github.io/docs/getting-started/installation#android)

Below you can see examples of how I'm editing the AndroidManifest, MainActivity.

![image](https://user-images.githubusercontent.com/45637344/186460725-7dc4747b-3ee1-499c-8a2f-cd6a927c7f77.png)

![image](https://user-images.githubusercontent.com/45637344/186632631-011e0e91-7b7d-47cf-902f-072dd347f095.png)

Am I overlooking something?
Thanks in advance!

**Comment by mihaiblaga89** [comment]
@kasinskas any ideas on this?

**Comment by kasinskas** [comment]
@mihaiblaga89 seems like it was the issue with Google Play Services not being enabled on the emulator https://github.com/react-native-google-cast/react-native-google-cast/issues/448, so can be closed most likely

**Comment by fabio-carvalho88** [comment]
hello @mihaiblaga89 @kasinskas, I had to ensure that my Android emulator had the Play Store and Google Play Services enabled after properly installing and configuring the package according to the [docs](https://react-native-google-cast.github.io/docs/getting-started/installation).

Everything went smoothly, regarding the iOS emulator.

**Comment by pauliusguzas** [comment]
Closing as solved
