### ISSUE TITLE
How to add Associated Domain Capability for iOS ?

### ISSUE THREAD

**Issue by himu243** [flexn-io/renative#913]
I want to add couple of Associated domains for my iOS App. Can someone please guide me through it like how do we do that in a ReNative Applciation?

**Comment by himu243** [comment]
I am able to add entitlements using, platforms.ios.entilements.Associated Domains. But I need to add the Capability also now. How do we add Capability?

**Comment by RosaryDarling** [comment]
Closing this ticket as it seems to be answered, although please feel free to reopen if the question persists
