### ISSUE TITLE
Keyboard addListener event not working in Android TV emulator.

### ISSUE THREAD

**Issue by 026binit** [flexn-io/renative#920]
keyboard addListener event not working in Android TV emulator. I don't have real Android TV devices so I am not sure it's working in real device.

None of below event worked

```
- keyboardWillShow
- keyboardDidShow
- keyboardWillHide
- keyboardDidHide
- keyboardWillChangeFrame
- keyboardDidChangeFrame
```

**Platform:-**
**Android TV**
` "rnv": "0.34.0",`
`"react-native": "0.63.4",`
`Emulator: Android TV (1080p) API 30`

**Comment by RosaryDarling** [comment]
Hi @026binit, could please try with the latest version and let us know if the issue still persists?

**Comment by RosaryDarling** [comment]
Closing this issue as stale until more details would be provided
