### ISSUE TITLE
[tvOS] Enable Debug Mode on Real Apple TV Device.

### ISSUE THREAD

**Issue by himanshuttn** [flexn-io/renative#921]
Can someone guide me how do we enable the debug mode on real Apple TV Device?

**Comment by aurimasmi** [comment]
Make a long press on the play/pause button on the remote, it will bring you developer menu on the screen where you can enable debugging

**Comment by RosaryDarling** [comment]
Closing this issue as it seem to be answered, although please feel free to reopen it if needed.
