### ISSUE TITLE
TTS(text to speach) Tizen TV

### ISSUE THREAD

**Issue by Alexandrusandy** [flexn-io/renative#932]
Hi i,we createa an app for tizen tv with renative,but the tts don't work so i cant upload my app to store,any solution to disable tts for tizen or implement corectly?

**Comment by RosaryDarling** [comment]
Hi @Alexandrusandy, could you please let me know which version are you using?

**Comment by RosaryDarling** [comment]
Closing this issue as stale until more details would be provided

**Comment by Alexandrusandy** [comment]
@RosaryDarling  i was using rnv version 0.33.0, i manage to fix these by adding <tizen:metadata key="http://samsung.com/tv/metadata/use.voiceguide" value="false"/> in my tizen index.html, but because of the library the index was overwrite and remove it ,so i build the project with tizen cli.
