### ISSUE TITLE
Storybook integration Issue

### ISSUE THREAD

**Issue by rohan3342** [flexn-io/renative#938]
**Hello Guys, and thank you for the amazing contribution and support.
I have been trying to add a storybook to the project, insisting not to eject the platforms with no luck.
Do you have any advice on how to make it possible easily?**

**Comment by rohan3342** [comment]
@pavjacko any updated?

**Comment by GabrieleKaceviciute** [comment]
Hello, @rohan3342 , thanks for reporting, is this still reproduced on latest version? Could you provide more information what package are you trying to integrate; what versions?

**Comment by pauliusguzas** [comment]
@rohan3342  Closing due to lack on activity, please reopen if this is still important
