### ISSUE TITLE
Navigation is not working on rnv@0.36.1. for webOS

### ISSUE THREAD

**Issue by rohan3342** [flexn-io/renative#950]
So recently, I upgraded my project from 0.34 to 0.36; I'm using webpack for web and webOS.

I was using `@react-navigation/stack` for WebOS while I was on `rnv@0.34`, but after I upgraded to `rnv@0.36`, it’s not rendering anything.

Do I have to use `react-router-dom` or `@reach/router` for navigation?

**Comment by GabrieleKaceviciute** [comment]
@rohan3342 Thanks for reporting, this will be checked

**Comment by pauliusguzas** [comment]
@rohan3342 this should not be the issue on latest rc's (latest being 1.0.0-rc.18)

**Comment by GabrieleKaceviciute** [comment]
Closing as answer has been provided, feel free to reopen if needed
