### ISSUE TITLE
Unable to override app/build.gradle through renative.json file

### ISSUE THREAD

**Issue by raj1823** [flexn-io/renative#952]
I want to override "compileSdkVersion" through renative.json file. However, it was working well till 0.34 version. After upgrading the project to 0.36.0, this override doesn't work anymore. 

Steps to reproduce:
1) in renative.json file, under android platform, I have specified "compileSdkVersion" key.
<img width="234" alt="Screenshot 2022-12-20 at 3 40 09 PM" src="https://user-images.githubusercontent.com/60693287/208641532-ad924cc7-c591-4d6a-8818-482c0b5164ed.png">

2) ran command : npx rnv run -p android -r
3) Check under platformBuilds/android/app/build.gradle file. It does not override the compileSDK version. 

NOTE: Happening for various keys as well!

**Comment by GabrieleKaceviciute** [comment]
@raj1823 thanks for reporting this issue, is this still reproduced on latest version?

**Comment by pauliusguzas** [comment]
@raj1823 you are adding `compileSdkVersion` property in wrong place, it should be added as below, checked on 0.37.1 and it works
```
  "platforms": {
    "android": {
      "compileSdkVersion": "33"
    }
```
