### ISSUE TITLE
Web Platform deployment/documentation recommendations

### ISSUE THREAD

**Issue by kevireilly** [flexn-io/renative#954]
Hey there.

I'm new to ReNative, so I usually assume that I'm missing something that may be apparent to others, but it seems as though the [Web Platform documentation](https://renative.org/docs/platforms/web) may be out of date relative to ReNative version 0.36.1. In particular, this line doesn't appear to represent that a `.next` folder alone is created in this directory when you do `rnv build -p web`:
```
your deployable web app folder will be located in ./platformBuilds/<APP_ID>_web/public
```

I was wondering if there are any other recommendations that people may have which might be good to further expand the Web Platform documentation for those that are new to ReNative and/or Next.js. I did manage to get something working locally based on some breadcrumbs from #953 that I'll detail below, I'm just not certain if this is the best recommendation at the moment.

### Modify next.config.js
Use Next.js [Output File Tracing](https://nextjs.org/docs/advanced-features/output-file-tracing) with the former `experimental` approach since, presumably, the version of Next.js in use within ReNative may be a little older:
```diff
diff --git a/next.config.js b/next.config.js
index a2ae8b3..58345c7 100644
--- a/next.config.js
+++ b/next.config.js
@@ -3,6 +3,9 @@ const path = require('path');
 
 const config = {
     projectRoot: path.resolve(__dirname),
+    experimental: {
+        outputStandalone: true,
+    },
 };
```

### Create a ReNative/Next.js Web Platform build
```
$ rnv build -p web
```

### Manually copy .next/static and public folders to the appropriate place
This was the tricky part to figure out relative to the Next.js documentation -- they actually need to be copied to the nested `platformBuilds/app_web` directory within the `standalone` directory. If you copy these directories in to the `standalone` folder itself, the page will likely be mostly white, lacking CSS, and otherwise will not be functional due to failing to retrieve (404) on the associated static assets.
```
$ cp -R platformBuilds/app_web/.next/static platformBuilds/app_web/.next/standalone/platformBuilds/app_web/.next 
$ cp -R public platformBuilds/app_web/.next/standalone/platformBuilds/app_web/
```

### Run the Next.js standalone server.js
If all goes well, you can then start the standalone server with vanilla Node.
```
$ node platformBuilds/app_web/.next/standalone/server.js
Listening on port 3000
```
And then load the Web Platform build in a browser (e.g. http://localhost:3000)

**Comment by mihaiblaga89** [comment]
@kevireilly thanks for the question! This depends on what type of app you're building, Static, SSR, SSG. If I remember correctly this would work perfectly for static, your website will be present in that output directory. However, I encountered the same issue with SSG, output directory would contain mostly nothing. In my case I was using the env variable `NEXT_PRIVATE_STANDALONE=true` to achieve the same thing as you. Will see what I can do about this

**Comment by mihaiblaga89** [comment]
@kevireilly small thought, you could automate all this with [hooks](https://renative.org/docs/guides/build_hooks) until we publish a fix.

**Comment by RosaryDarling** [comment]
Closing this issue as it seems to be answered but feel free to reopen it if the issue persists
