### ISSUE TITLE
Source maps for web are not showing original code but ES5

### ISSUE THREAD

**Issue by vladinko0** [flexn-io/renative#956]
**Describe the bug**
Source maps for web are not showing original code but ES5

**To Reproduce**

1. Run command 'rnv new testproject'
2. In wizard select `renative-template-hello-world`
3. Run command 'npx rnv run -p web'
   -  not needed to turn on source maps. They are there by default. It is caused by default next option `devtool: eval-source-map` of webpack.

**Expected behavior**
Inspect the web (F12) and you can see original code of `_app.js`:
```
import React from 'react';
import { useRouter } from 'next/router';
import { View } from 'react-native';
import Menu from '../components/menu';
import { themeStyles, ThemeProvider } from '../config';

export default function MyApp({ Component, pageProps }) {
    const router = useRouter();
    return (
        <ThemeProvider>
            <Menu focusKey="menu" router={router} />
            <View style={themeStyles.appContainer}>
                <Component {...pageProps} />
            </View>
        </ThemeProvider>
    );
}
```
But I see ES5 code:

![Screenshot 2023-01-02 at 08 45 09](https://user-images.githubusercontent.com/16008547/210521018-9b7b332a-bd58-4f92-9822-c7fb664eca60.png)

**Desktop (please complete the following information):**

-   OS: [macOS 12.6]
-   Node Version [v16.14.2]
-   RNV Version [e.g. 0.35.4]

I created also clean next.js project and the source code is correct:

![Screenshot 2023-01-04 at 10 22 44](https://user-images.githubusercontent.com/16008547/210523466-51cea77d-7899-4f5c-8403-bc2f778a700d.png)

**Comment by pauliusguzas** [comment]
Related to https://github.com/flexn-io/renative/issues/953

**Comment by ElenaDiachenko** [comment]
this is no longer the issue in 1.0.0-rc.18.
