### ISSUE TITLE
Couldn't determine CLI location. -  android Wear

### ISSUE THREAD

**Issue by soumen-web** [flexn-io/renative#963]
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > Couldn't determine CLI location. Please set `project.ext.react.cliPath` to the path of the react-native cli.js
   
  -----------------_
  Please help asap how to edit app/android/build.gradle. 
  How to add project.ext.react.cliPath

**Comment by GabrieleKaceviciute** [comment]
@soumen-web thanks for reporting, could you provide rnv and node versions, os type? What exact command are you running?

**Comment by pauliusguzas** [comment]
Closing as no answer has been provided
