### ISSUE TITLE
renative  "version": "0.36.1"  getting issue in webos  build

### ISSUE THREAD

**Issue by MarotiKathoke** [flexn-io/renative#964]
"version": "0.36.1"  getting project output folder empty   in WebOS  ,

Command failed with exit code 255: /opt/webOS_TV_SDK/CLI/bin/ares-package -o /Users/mk/Desktop/Projects/app/platformBuilds/app_webos/output /Users/mk/Desktop/Projects/app/platformBuilds/app_webos -n
ares-package ERR! uncaughtException Error: ENOENT: no such file or directory, open '/Users/mk/Desktop/Projects/app/platformBuilds/app_webos/index.html'
at makeError (/Users/mk/Desktop/Projects/app/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
at handlePromise (/Users/mk/Desktop/Projects/app/node_modules/rnv/node_modules/execa/index.js:118:26)
at process

**Comment by MarotiKathoke** [comment]
Command failed with exit code 255: /opt/webOS_TV_SDK/CLI/bin/ares-package -o /Users/mk/Desktop/Projects/app/platformBuilds/app_webos/output /Users/mk/Desktop/Projects/app/platformBuilds/app_webos -n
ares-package ERR! uncaughtException Error: ENOENT: no such file or directory, open '/Users/mk/Desktop/Projects/app/platformBuilds/app_webos/index.html'
    at makeError (/Users/mk/Desktop/Projects/app/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/mk/Desktop/Projects/app/node_modules/rnv/node_modules/execa/index.js:118:26)
    at process

**Comment by GabrieleKaceviciute** [comment]
@MarotiKathoke thanks for reporting this issue. I can't reproduce it on version 0.37.0-canary.13. Please update version and try again

**Comment by bruno-sartori** [comment]
any updates on this?

**Comment by bruno-sartori** [comment]
I've tested on version 0.37.2 and the error still occurs.

`                                                  │
│  Engine ($.platforms.webos.engine): engine-rn-web                            │
│  Template: @rnv/template-starter@0.37.2                                      │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): release                                                  │
│  Bundle assets ($.platforms.webos.bundleAssets): true                        │
│  Target (-t): emulator                                                       │
│  Supported Platforms: webos                                                  │
│  Env Info: win32 | x64 | node v18.16.1                                       │
│  Executed Time: 0h:0m:10s:554ms                                              │
│                                                                              │
│ [ success ] [run] Compiled successfully.

│ [ error ] [run] COMMAND:

C:\webOS_TV_SDK\CLI\bin\ares-package.cmd -o C:\Users\BrunoSartori\Documents\Projects\agile\prism\teste\teste\platformBuilds\app_webos\output C:\Users\BrunoSartori\Documents\Projects\agile\prism\teste\teste\platformBuilds\app_webos -n

FAILED with ERROR:

Command failed with exit code 4294967295: C:\webOS_TV_SDK\CLI\bin\ares-package.cmd -o C:\Users\BrunoSartori\Documents\Projects\agile\prism\teste\teste\platformBuilds\app_webos\output C:\Users\BrunoSartori\Documents\Projects\agile\prism\teste\teste\platformBuilds\app_webos -n
ares-package ERR! [Tips]: The specified path does not exist <C:\Users\BrunoSartori\Documents\Projects\agile\prism\teste\teste\platformBuilds\app_webos\index.html>

ares-package ERR! [Tips]: The specified path does not exist <C:\Users\BrunoSartori\Documents\Projects\agile\prism\teste\teste\platformBuilds\app_webos\index.html>

Error: Command failed with exit code 4294967295: C:\webOS_TV_SDK\CLI\bin\ares-package.cmd -o C:\Users\BrunoSartori\Documents\Projects\agile\prism\teste\teste\platformBuilds\app_webos\output C:\Users\BrunoSartori\Documents\Projects\agile\prism\teste\teste\platformBuilds\app_webos -n
ares-package ERR! [Tips]: The specified path does not exist <C:\Users\BrunoSartori\Documents\Projects\agile\prism\teste\teste\platformBuilds\app_webos\index.html>
    at makeError (C:\Users\BrunoSartori\Documents\Projects\agile\prism\teste\teste\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\BrunoSartori\Documents\Projects\agile\prism\teste\teste\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


│                                                                              │
│  Project location:                                                           │
│  C:\Users\BrunoSartori\Documents\Projects\agile\prism\teste\teste\platformBuilds\app_webos
└──────────────────────────────────────────────────────────────────────────────┘`

**Comment by pauliusguzas** [comment]
0.37.3
```
pauliusguzas@Pauliuss-MBP rnvtest % rnv build -p webos -r -s

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 0.37.3                                                       │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv build -p webos -r -s                                            │
│        Start Time: 9/8/2023, 11:53:01 AM                                     │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngine:engine-core[1]
[ task ] configureRuntimeDefaults[1] appId:null
[ task ] checkAndMigrateProject[1]
[ task ] loadPluginTemplates[1]
[ task ] _parsePluginTemplateDependencies[1] scope:root
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] _generatePlatformTemplatePaths[1]
[ task ] checkAndBootstrapIfRequired[1]
[ task ] loadIntegrations[1]
[ task ] loadEngines[1]
[ task ] loadEnginePluginDeps[1]
[ task ] loadEnginePackageDeps[1]
[ task ] registerEngine:engine-rn-web[1]
[ task ] findSuitableTask[1]
[ info ] Current Engine: engine-rn-web path: ./node_modules/@rnv/engine-rn-web
[ task ] registerMissingPlatformEngines[1]
[ task ] initializeTask[1] build
[ task ] => [build]
[ task ] [build] checkIfProjectAndNodeModulesExists[1]
[ hook ] [build] executePipe ('build:before')
[ hook ] [build] buildHooks Build hooks not complied. BUILDING...
[ task ] [build] taskRnvBuild[1] parent:null
[ task ] => [build] => [package]
[ hook ] [package] executePipe ('package:before')
[ task ] [package] taskRnvPackage[1] parent:build
[ task ] => [package] => [configure]
[ hook ] [configure] executePipe ('configure:before')
[ task ] [configure] taskRnvConfigure[1]
[ task ] => [configure] => [platform configure]
[ hook ] [platform configure] executePipe ('platform:configure:before')
[ task ] [platform configure] taskRnvPlatformConfigure[1]
[ task ] => [platform configure] => [project configure]
[ hook ] [project configure] executePipe ('project:configure:before')
[ task ] [project configure] taskRnvProjectConfigure[1]
[ task ] [project configure] checkAndMigrateProject[2]
[ task ] [project configure] loadPluginTemplates[2]
[ task ] [project configure] _parsePluginTemplateDependencies[2] scope:root
[ task ] [project configure] parseRenativeConfigs[2]
[ task ] [project configure] getWorkspaceDirPath[2]
[ task ] [project configure] _generatePlatformTemplatePaths[2]
[ task ] => [project configure] => [workspace configure]
[ task ] [workspace configure] taskRnvWorkspaceConfigure[1]
[ task ] <= [project configure] <= workspace configure
[ task ] [project configure] checkIfTemplateConfigured[1]
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[1] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] [project configure] checkCrypto[1]
[ task ] [project configure] configureRuntimeDefaults[2] appId:app
[ task ] [project configure] applyTemplate[1] @rnv/template-starter=>undefined
[ task ] [project configure] _applyTemplate[1] current:@rnv/template-starter selected:undefined
[ task ] [project configure] configureRuntimeDefaults[3] appId:app
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[2] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] => [project configure] => [app configure]
[ hook ] [app configure] executePipe ('app:configure:before')
[ task ] [app configure] taskRnvAppConfigure[1]
[ task ] [app configure] listAppConfigsFoldersSync[1] ignoreHiddenConfigs:true
[ task ] [app configure] loadPluginTemplates[3]
[ task ] [app configure] _parsePluginTemplateDependencies[3] scope:root
[ task ] [app configure] parseRenativeConfigs[3]
[ task ] [app configure] generateBuildConfig[1] size:193.83 KB
[ task ] [app configure] getWorkspaceDirPath[3]
[ task ] [app configure] generateBuildConfig[2] size:193.83 KB
[ task ] [app configure] generateBuildConfig[3] size:193.83 KB
[ task ] [app configure] generateBuildConfig[4] size:193.83 KB
[ task ] [app configure] _generatePlatformTemplatePaths[3]
[ task ] [app configure] generateBuildConfig[5] size:206.81 KB
[ task ] [app configure] generateBuildConfig[6] size:206.81 KB
[ task ] [app configure] getWorkspaceDirPath[4]
[ task ] [app configure] generateBuildConfig[7] size:206.81 KB
[ task ] [app configure] generateLocalConfig[1] resetAppId:false
[ task ] [app configure] generateBuildConfig[8] size:206.81 KB
[ info ] [app configure] Current App Config: app
[ hook ] [app configure] executePipe ('app:configure:after')
[ task ] <= [project configure] <= app configure
[ task ] [project configure] versionCheck[1]
[ task ] [project configure] versionCheck:rnvRunner:0.37.3,rnvProject:0.37.3[1]
[ task ] [project configure] configureEngines[1]
[ task ] [project configure] resolvePluginDependants[1]
[ task ] [project configure] configurePlugins[1]
[ task ] [project configure] configureRuntimeDefaults[4] appId:app
[ task ] [project configure] copyRuntimeAssets[1]
[ task ] [project configure] configureTemplateFiles[1]
[ task ] [project configure] checkAndCreateGitignore[1]
[ task ] [project configure] checkAndCreateBabelConfig[1]
[ task ] [project configure] generateRuntimeConfig[1]
[ task ] [project configure] overrideTemplatePlugins[1]
[ task ] [project configure] parsePlugins[1]
[ info ] [project configure] /react-native overriden by: /@flexn/plugins/pluginTemplates/react-native/overrides@0.67.2
[ info ] [project configure] /@react-native-community/cli-platform-ios overriden by: /@flexn/plugins/pluginTemplates/@react-native-community/cli-platform-ios/overrides
[ info ] [project configure] /react-native-gesture-handler overriden by: /@flexn/plugins/pluginTemplates/react-native-gesture-handler/overrides
[ info ] [project configure] /react-native-tvos overriden by: /@flexn/plugins/pluginTemplates/react-native-tvos/overrides@0.66.3-1
[ info ] [project configure] /next/dist/lib/find-pages-dir.js overriden by: /@flexn/plugins/pluginTemplates/next/overrides.json
[ task ] [project configure] parseFonts[1]
[ task ] [project configure] parsePlugins[2]
[ hook ] [project configure] executePipe ('project:configure:after')
[ task ] <= [platform configure] <= project configure
[ task ] [platform configure] isPlatformSupported[1]
[ task ] [platform configure] checkAndConfigureSdks[1]
[ task ] [platform configure] checkAndConfigureWebosSdks:webos[1]
[ task ] [platform configure] isBuildSchemeSupported[1]
[ task ] [platform configure] You need to specify scheme[1]
? Pick one of available buildSchemes test (Hello ReNative - Use to run automation)
[ info ] [platform configure] Current Build Scheme: test
[ task ] [platform configure] checkSdk[1]
[ task ] [platform configure] _isSdkInstalled[1]
[ task ] [platform configure] checkAndConfigureAndroidSdks[1] (/Users/pauliusguzas/Library/Android/sdk)
[ task ] [platform configure] configureRuntimeDefaults[5] appId:app
[ task ] => [platform configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[3] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [platform configure] <= install
[ task ] [platform configure] [1] taskRnvPlatformConfigure hasBuildFolderPresent:true
[ info ] [platform configure] You passed -r argument. "platformBuilds/app_webos" CLEANING...DONE
[ task ] [platform configure] cleanPlatformBuild[1]
[ task ] [platform configure] createPlatformBuild[1]
[ task ] [platform configure] injectPlatformDependencies[1]
[ hook ] [platform configure] executePipe ('platform:configure:after')
[ task ] <= [configure] <= platform configure
[ task ] [configure] configureEntryPoint[1]
[ task ] [configure] copySharedPlatforms[1]
[ task ] [configure] configureWebOSProject[1]
[ task ] [configure] copyAssetsFolder[1]
[ info ] [configure] Found custom assetSources at ./node_modules/@flexn/assets-renative-outline/assets/webos. Will be used to generate assets.
[ task ] [configure] configureCoreWebProject[1]
[ task ] [configure] _configureProject[1]
[ task ] [configure] copyBuildsFolder[1]
[ task ] [configure] copyTemplatePluginsSync[1] (./platformBuilds/app_webos)
[ task ] [configure] parsePlugins[1]
[ hook ] [configure] executePipe ('configure:after')
[ task ] <= [package] <= configure
[ hook ] [package] executePipe ('package:after')
[ task ] <= [build] <= package
[ task ] [build] buildWebOSProject[1]
[ task ] [build] buildCoreWebpackProject[1]
[ task ] [build] parsePlugins[2]
[ error ] [build] Failed to compile.

TS2786: 'View' cannot be used as a JSX component.
  Its instance type 'View' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("/Users/pauliusguzas/Desktop/rnvtest/node_modules/@types/react-native/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
    23 |
    24 |     return (
  > 25 |         <View style={theme.styles.container}>
       |          ^^^^
    26 |             <Image
    27 |                 style={theme.styles.image}
    28 |                 source={ICON_LOGO}


pauliusguzas@Pauliuss-MBP rnvtest %
```

**Comment by ElenaDiachenko** [comment]
1.0.0-canary.1
`[ success ] [build] Compiled successfully.

[ info ] [build] File sizes after gzip:

  129.76 kB  build/static/js/main.9bfabebd.js
The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The platformBuilds/template_webos/build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

✖ FAILED: /Users/olenadiachenko/Library/webOS_TV_SDK/CLI/bin/ares-package -o /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/output /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos -n
COMMAND: 

/Users/olenadiachenko/Library/webOS_TV_SDK/CLI/bin/ares-package -o /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/output /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos -n 

FAILED with ERROR: 

Command failed with exit code 255: /Users/olenadiachenko/Library/webOS_TV_SDK/CLI/bin/ares-package -o /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/output /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos -n
ares-package ERR! [Tips]: The specified path does not exist </Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/index.html>

ares-package ERR! [Tips]: The specified path does not exist </Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/index.html>

Error: Command failed with exit code 255: /Users/olenadiachenko/Library/webOS_TV_SDK/CLI/bin/ares-package -o /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/output /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos -n
ares-package ERR! [Tips]: The specified path does not exist </Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/index.html>
    at makeError (/Users/olenadiachenko/GitHub/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/olenadiachenko/GitHub/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ rnv build -p webos -r - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/6/2023, 8:07:18 PM                                         │
│  $ rnv build -p webos -r                                                     │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.1                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.1                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): webos                                                        │
│  Engine ($.platforms.webos.engine): engine-rn-web                            │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): emulator                                                       │
│  Reset Project (-r): true                                                    │
│  Supported Platforms: webos                                                  │
│  Env Info: darwin | x64 | node v18.18.0                                      │
│  Executed Time: 0h:0m:9s:59ms                                                │
│                                                                              │
│ [ success ] [build] Compiled successfully.

│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_webos                                             │`

**Comment by ElenaDiachenko** [comment]
1.0.0-canary.1
`[ success ] [build] Compiled successfully.

[ info ] [build] File sizes after gzip:

  129.76 kB  build/static/js/main.9bfabebd.js
The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The platformBuilds/template_webos/build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

✖ FAILED: /Users/olenadiachenko/Library/webOS_TV_SDK/CLI/bin/ares-package -o /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/output /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos -n
COMMAND: 

/Users/olenadiachenko/Library/webOS_TV_SDK/CLI/bin/ares-package -o /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/output /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos -n 

FAILED with ERROR: 

Command failed with exit code 255: /Users/olenadiachenko/Library/webOS_TV_SDK/CLI/bin/ares-package -o /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/output /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos -n
ares-package ERR! [Tips]: The specified path does not exist </Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/index.html>

ares-package ERR! [Tips]: The specified path does not exist </Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/index.html>

Error: Command failed with exit code 255: /Users/olenadiachenko/Library/webOS_TV_SDK/CLI/bin/ares-package -o /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/output /Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos -n
ares-package ERR! [Tips]: The specified path does not exist </Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_webos/index.html>
    at makeError (/Users/olenadiachenko/GitHub/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/olenadiachenko/GitHub/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ rnv build -p webos -r - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/6/2023, 8:07:18 PM                                         │
│  $ rnv build -p webos -r                                                     │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.1                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.1                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): webos                                                        │
│  Engine ($.platforms.webos.engine): engine-rn-web                            │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): emulator                                                       │
│  Reset Project (-r): true                                                    │
│  Supported Platforms: webos                                                  │
│  Env Info: darwin | x64 | node v18.18.0                                      │
│  Executed Time: 0h:0m:9s:59ms                                                │
│                                                                              │
│ [ success ] [build] Compiled successfully.

│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_webos                                             │`
