### ISSUE TITLE
Target API level requirement google play store

### ISSUE THREAD

**Issue by happyDemon** [flexn-io/renative#971]
Google is enforcing the following to apps that are/will be published to the Google app store:

Starting August 31, 2023:

New apps and app updates must target API level 33 to be submitted to Google Play (Wear OS must target API 30)

Existing apps must target API level 31 or above to remain available to users on devices running Android OS higher than your app's target API level. Apps that target API level 30 or below (target API level 29 or below for Wear OS), will only be available on devices running Android OS same or lower than your apps’ target API level.

This is a bit worry some (the android wear platform currently runs on sdk 23 for example)

https://support.google.com/googleplay/android-developer/answer/11926878?hl=en

**Comment by GabrieleKaceviciute** [comment]
@happyDemon thanks for reporting, this will be checked

**Comment by pauliusguzas** [comment]
@happyDemon All android platforms are now targeting SDK 33
