### ISSUE TITLE
Could not find com.yqritc:android-scalablevideoview:1.0.4

### ISSUE THREAD

**Issue by saimirg** [flexn-io/renative#975]
Installation commands:
1. npm install rnv -g
2. rnv new
3. rnv plugin add react-native-video

All above run successful; when trying to run on androdtv it is generating the following error:

FAILED with ERROR: 

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
 > Could not find com.yqritc:android-scalablevideoview:1.0.4.
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-video:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-video:debugCompileClasspath'.
 > Could not find com.yqritc:android-scalablevideoview:1.0.4.

Command failed with exit code 1: ./gradlew assembleDebug -x bundleReleaseJsAndAssets

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.yqritc:android-scalablevideoview:1.0.4.
     Searched in the following locations:
       - file:/Users/user/Desktop/sgrn-demo/rnv19april/node_modules/react-native/android/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - file:/Users/user/Desktop/sgrn-demo/rnv19april/node_modules/jsc-android/dist/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - https://repo.maven.apache.org/maven2/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - https://dl.google.com/dl/android/maven2/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - https://www.jitpack.io/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
     Required by:
         project :app > project :react-native-video

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-video:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-video:debugCompileClasspath'.
   > Could not find com.yqritc:android-scalablevideoview:1.0.4.
     Required by:
         project :react-native-video

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

**Comment by maciejsiiminski** [comment]
add
`
jcenter() {
            content {
                includeModule("com.yqritc", "android-scalablevideoview")
            }
        }
`
to your android\build.gradle. Works for me. You can alternatively add whole center to build.gradle, but center is no longer maintained and often offline, so I would not recommend that.

**Comment by saimirg** [comment]
@maciejsiiminski we tried but it doesnt work, is it because jcenter service is down ?

We made the change as per your recommendation but on but the moment you run "nvm run", the running script will restore build.gradle to default, deleting what we added.

**Comment by maciejsiiminski** [comment]
Ok, so you have to eject the platform you have this problem using renative cli. I think the command is platform eject <platformName>. After you do so, a new folder called platform templates will be created. From now the reantive will use this folder as the template instead the default one from the @rnv node module. Here you can change all the gradle and other compilation-related files and they will not be overwritten. Platform builds are overwritten on every compilation so changing them doesn't do a thing.

**Comment by maciejsiiminski** [comment]
That's a problem but I think it can be overcome. You can add the platformTemplatesDirs property to the path in your renative.json like this.
```
"platformTemplatesDirs": {
            "androidtv": "./platformTemplates"
        }
```
My whole path object in renative.json looks like this. 
```
"paths": {
        "appConfigsDir": "./appConfigs",
        "platformAssetsDir": "./platformAssets",
        "platformBuildsDir": "./platformBuilds",
        "platformTemplatesDirs": {
            "androidtv": "./platformTemplates"
        }
    },
```
Then you should create a folder platformTemplates and copy node_modules/@rnv/engine-rn/templates/platforms/androidtv folder into it. Then in theory it should build androidtv from this folder and you can change this template however you want. 

I reverse-engineered this solution so can't guarantee it would work, but I hope so. Alternatively, you can just edit the files inside the template in node modules (previously mentioned path) but keep in mind, that the changes will be lost with every newly installed/updated node module.

**Comment by rameshep1989** [comment]
@maciejsiiminski done as you said but still, I'm getting the same error. Any idea?

**Comment by pauliusguzas** [comment]
@saimirg Thanks for reporting this issue, could you provide rnv and node versions, os type?

**Comment by mihaiblaga89** [comment]
Please try again with version 0.37, it should fix the issue with the missing plugins. If not, feel free to reopen.
