### ISSUE TITLE
How to make renative use my forked version of react-native?

### ISSUE THREAD

**Issue by maciejsiiminski** [flexn-io/renative#976]
I've been developing an androidtv application using renative and it's going well but unfortunately, we encountered some random crushes. Long story short, it is an issue that happens on some android 12 devices and is still not fixed by react-native team but can be somewhat mitigated by modifying react-native java code. I forked the react-native-tvos plugin, modified the code, and installed it as a custom node module through package.json. Unfortunately, I can't figure out how to make renative use this version of react-native-tvos instead of the original one. How do I configure renative to do so?

**Comment by pauliusguzas** [comment]
@maciejsiiminski thanks for this question, we will be looking into this
