### ISSUE TITLE
Please provide update for latest version of React Native, Tizen OS and for other OS

### ISSUE THREAD

**Issue by HarshBMouritech** [flexn-io/renative#980]
**Please provide update for latest version of React Native, Tizen OS and for other OS**
When I created new project using below link, I got react native version 0.67.2 but latest React Native version is 0.71.
For Tizen TV, you are supporting Tizen 5.0, 4.0, 3.0 but  and latest Tizen TV OS is 7.0 M2.

**Please provide update for latest versions**

**Comment by pauliusguzas** [comment]
@HarshBMouritech thanks for providing us feedback, we are always trying to keep versions updated and your suggestions will be looked into.

**Comment by HarshBMouritech** [comment]
Hi @pauliusguzas, Thanks for the update and I want to tell you is whatever you built is amazing. I will be waiting for your next update.
