### ISSUE TITLE
Cannot find module ./src/cat

### ISSUE THREAD

**Issue by RedMunroe** [flexn-io/renative#982]
**Describe the bug**
Cannot find module './src/cat'
Require stack:
/Users/user/Paraguas/code/company/tv/project-manhattan/buildHooks/dist/index.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/dist/core/projectManager/buildHooks.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/dist/core/taskManager/index.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/dist/core/setupManager/base.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/dist/core/setupManager/linux.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/dist/core/setupManager/index.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/dist/core/sdkManager/installer.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/dist/core/platformManager/index.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/dist/core/projectManager/index.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/dist/core/pluginManager/index.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/dist/core/engineManager/index.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/dist/core/runtimeManager/index.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/dist/cli/index.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/dist/index.js
- /Users/user/.nvm/versions/node/v18.13.0/lib/node_modules/rnv/bin/index.js

**To Reproduce**

1. create new project 
2. try and run tvos

**Expected behavior**
The app should boot a apple tv simulator with the code https://github.com/shelljs/shelljs/issues/1035

**Screenshots or copy&paste**
If applicable, copy&paste the output of the command. **Run the command with `-i` to get more debugging informations**

**Desktop (please complete the following information):**

-   OS: OSX
-   Node Version [e.g. v18.13.0]
-   RNV Version [e.g. 0.36.1]

**Additional context**
it appears to be an issue in shellJS... that they dont appear to want to support.

**Comment by pauliusguzas** [comment]
@MayorMunroe thanks for reporting this issue! what template and what version did you use?

**Comment by pauliusguzas** [comment]
@RedMunroe any update on this?
