### ISSUE TITLE
WebView not working for Android Tv

### ISSUE THREAD

**Issue by elStranger** [flexn-io/renative#985]
Project Version ($package.version): 0.1.0
Workspace ($.workspaceID): rnv
Platform (-p): androidtv
Engine ($.platforms.androidtv.engine): engine-rn-tvos
Template: @flexn/template@0.18.0-alpha.10
App Config (-c): app
Build Scheme (-s): debug
Target (-t): Android_TV_720p_API_22
Supported Platforms: androidtv, firetv
Env Info: darwin I x64 I node v16.16.0
Executed Time: Oh:3m: 44s:905ms
[ warn ] [project configure] This project uses encrypted files but you don't
Project location:
•/platformBuilds/app_androidtv

the emulator start correctly everything is working fine but when in install react-native-webview it says that `TurboModuleRegistry.getEnforcing(...): 'RNCWebView' could not be found. Verify that a module by this name is registered in the native binary.`

when i change the version for a older one : `error equireNativeComponent: “RNCWebView” was not found in the UIManager`

i tried npx react-native link react-native-webview not working do you have an idea?

**Comment by pauliusguzas** [comment]
@elStranger thanks for reporting this issue, what rnv version are you using?

**Comment by elStranger** [comment]
Thank you for your quick answer. here's my package.json 

`
{
    "devDependencies": {
        "@rnv/engine-rn-tvos": "0.36.1",
        "@rnv/template-starter": "0.36.1",
        "@types/react": "18.0.11",
        "@types/react-dom": "18.0.5",
        "@types/react-native": "0.67.2",
        "rnv": "0.36.1",
        "typescript": "4.5.4"
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    },
    "name": "MT",
    "version": "0.1.0",
    "dependencies": {
        "@flexn/typescript": "0.1.4",
        "@noriginmedia/react-spatial-navigation": "2.12.9",
        "@react-native-community/cli": "^6.0.0",
        "@react-native-community/cli-platform-ios": "^6.0.0",
        "@react-native-community/masked-view": "0.1.6",
        "@react-native-community/viewpager": "2.0.2",
        "@react-navigation/bottom-tabs": "5.1.1",
        "@react-navigation/core": "5.12.3",
        "@react-navigation/drawer": "5.9.0",
        "@react-navigation/material-bottom-tabs": "5.1.1",
        "@react-navigation/material-top-tabs": "5.1.1",
        "@react-navigation/native": "5.7.3",
        "@react-navigation/routers": "5.1.0",
        "@react-navigation/stack": "5.9.0",
        "@react-navigation/web": "1.0.0-alpha.9",
        "@rnv/renative": "0.36.1",
        "hash-source": "1.0.4",
        "metro-cache": "^0.76.5",
        "react": "18.1.0",
        "react-art": "18.1.0",
        "react-dom": "18.1.0",
        "react-native": "0.67.2",
        "react-native-gesture-handler": "1.10.3",
        "react-native-google-cast": "4.2.4",
        "react-native-reanimated": "1.13.3",
        "react-native-safe-area-context": "3.1.0",
        "react-native-safe-area-view": "0.14.5",
        "react-native-screens": "2.2.0",
        "react-native-tab-view": "2.13.0",
        "react-native-tvos": "0.66.3-1",
        "react-native-vector-icons": "8.1.0",
        "react-native-web": "0.18.0",
        "react-native-web-image-loader": "0.0.5",
        "react-router-dom": "6.3.0",
        "tslib": "^2.5.3"
    }
}

`

**Comment by elStranger** [comment]
Hello thank you for you answer here's my package.json `{
    "devDependencies": {
        "@flexn/template": "0.18.0-alpha.10",
        "@rnv/engine-rn-tvos": "0.36.1",
        "@types/react": "17.0.37",
        "rnv": "0.36.1",
        "typescript": "4.5.4"
    },
    "name": "mt-a",
    "version": "0.1.0",
    "dependencies": {
        "@flexn/sdk": "0.18.0-alpha.10",
        "@flexn/typescript": "0.1.4",
        "@lightningjs/cli": "2.7.2",
        "@lightningjs/sdk": "4.3.3",
        "@react-native-community/cli": "^6.0.0",
        "@react-native-community/cli-platform-ios": "^6.0.0",
        "@react-native-community/masked-view": "0.1.6",
        "@react-native-windows/cli": "0.67.1",
        "@react-navigation/bottom-tabs": "5.1.1",
        "@react-navigation/core": "5.12.3",
        "@react-navigation/drawer": "5.11.4",
        "@react-navigation/material-bottom-tabs": "5.2.12",
        "@react-navigation/material-top-tabs": "5.3.10",
        "@react-navigation/native": "5.7.3",
        "@react-navigation/native-stack": "5.0.5",
        "@react-navigation/routers": "5.1.0",
        "@react-navigation/stack": "5.9.2",
        "@react-navigation/web": "1.0.0-alpha.9",
        "@rnv/renative": "0.36.1",
        "next": "12.0.9",
        "react": "18.1.0",
        "react-art": "18.1.0",
        "react-dom": "18.1.0",
        "react-native": "0.67.2",
        "react-native-gesture-handler": "1.10.3",
        "react-native-google-cast": "4.1.2",
        "react-native-media-query": "2.0.0",
        "react-native-reanimated": "1.13.3",
        "react-native-safe-area-context": "3.1.0",
        "react-native-screens": "2.2.0",
        "react-native-tvos": "0.66.3-1",
        "react-native-vector-icons": "8.1.0",
        "react-native-web": "0.18.0",
        "react-native-webview": "10.10.2",
        "react-native-webview-bridge": "^0.40.1",
        "react-native-windows": "0.67.3",
        "tslib": "2.3.1"
    }
}
`

**Comment by pauliusguzas** [comment]
@elStranger I copied your package.json and tried to run simulator, it ran without any issues, also did not notice any error in logs. At which stage are you getting this issue?

**Comment by elStranger** [comment]
Thank you for your support. I really do appreciate

The issue isn't running the simulator but the webview package. My simulator starts and everything works well (if i comment on the webview part). so when I try to add WebView I have a red screen in my emulator. I even tried to add WebViewBridge instead of Webview. same results.
here's more info...

`
**Android Tv (1080p) API 30 | x86 | Android 11.0 | Google Tv**

➜   JAVA_HOME=`/usr/libexec/java_home -v 11`
➜  npm -v
7.5.1
➜  node -v
v15.8.0
`

can you share your boilerplate, so I can test it on my Mac?

**Comment by mihaiblaga89** [comment]
@elStranger don't try to install plugins that need manual configs with just npm. Add it in `renative.json` plugins section as 
```
"plugins": {
        "react-native-webview": "source:rnv"
    },
```
and next time your run rnv it will install it and do all the required steps. However do keep in mind that this will not work for every package, just the ones supported. For exotic ones you might need to do a bit of config yourself. Reference https://github.com/flexn-io/renative/blob/canary/packages/rnv/pluginTemplates/renative.plugins.json

**Comment by mihaiblaga89** [comment]
closing this, feel free to reopen if needed
